### ISSUE TITLE
Enforce conformity of the 2017 React project packages

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#10]
During 2017 project season, the 5 React front-end projects were separate repos that shared a *goal* of conforming to common libraries and versions, but in practice didn't quite get there.

When the 5 projects were combined together with other dependent libraries to form the [Civic monorepo](https://github.com/hackoregon/civic), the need grew for conformance between these 5 packages' configuration.

Until these packages have a reasonable level of conformity amongst themselves, Hack Oregon will lack a working example of how they intend to manage multiple web apps in a single monorepo, and as additional packages get added, the problem won't get better (and could get worse).

Task list - first pass:
- [ ] Identify any duplicate dependencies between the master `/package.json` and the `package.json` files in the 5 packages under `/packages/` - `budget`, `emergency-response`, `homelesness`, `housing` and `transportation`.
- [ ] Remove the duplicates - same package, same version - from the 2017 projects' `package.json`
- [ ] Test and upgrade the versions for any packages running an older version of a duplicate dependency, then remove the now-duplicate version from the 2017 project

Task list - second pass:
- [ ] Identify any dependencies that are common to all five of the 2017 packages' `package.json` configurations
- [ ] Determine the lowest supported version for each of the common dependencies - i.e. the lowest version used by any of the five projects
- [ ] Migrate that dependency to the master `/package.json` 
- [ ] Identify the highest supported version for each from any of the 2017 projects - i.e. the highest version used by any of the five projects
- [ ] Test and upgrade the version for those projects that were running a version less than that highest version
- [ ] Remove the duplicate dependencies from 2017 projects' `package.json` once all projects have upgraded to the version declared in the master `/package.json`

If any project either "look wonky" or fail one of their test cases when a dependency version is upgraded, that dependency will be left hard-coded in the projects' `package.json` and will be listed here as a bug to be fixed.

**Comment by DingoEatingFuzz** [comment]
Out of scope for the devops team and devops projects.
