### ISSUE TITLE
Create/implement task definition for 2018 Disaster-Resilience-Service project

### ISSUE THREAD

**Issue by iant01** [hackoregon/civic-devops#103]
Create the service sub directory and service.yaml file for use in getting the service task definition into ECS.

**Comment by MikeTheCanuck** [comment]
Environment variables expected by the container to be passed in from ECS at runtime:
- PROJECT_NAME (in `production-docker-entrypoint.sh`)
- DJANGO_SECRET_KEY (in `settings.py`)
- POSTGRES_PASSWORD (in `settings.py`)
- POSTGRES_NAME (in `settings.py`)
- POSTGRES_USER (in `settings.py`)
- POSTGRES_HOST (in `settings.py`)
- POSTGRES_PORT (in `settings.py`)

**Comment by znmeb** [comment]
POSTGRES_NAME is the database name, right??

**Comment by nam20485** [comment]
@znmeb Correct, POSTGRES_NAME is the postgres DB name

**Comment by nam20485** [comment]
@MikeTheCanuck Your list is close, just need to add:

```
DEBUG=False
```

(Taken from: https://github.com/hackoregon/disaster-resilience-backend/blob/development/production-docker-compose.yml)

**Comment by MikeTheCanuck** [comment]
If the variable is only needed in a `docker-compose` file, then we don't need to read it into the container.

It looks like the variable is declared and used in [`settings.py`](https://github.com/hackoregon/disaster-resilience-backend/blob/development/backend/settings.py#L26), and if we never injected a different value, the default of `TRUE` will still work.

It might not be the intended effect for production, in which case it's worth considering whether to set line 26 = `FALSE` instead, and override it with the `.env` file that the developer has to use anyway.

**Comment by MikeTheCanuck** [comment]
PROJECT_NAME="backend"
