### ISSUE TITLE
Document details for backend repos to use when pushing docker image to ECR

### ISSUE THREAD

**Issue by nam20485** [hackoregon/civic-devops#105]
One of the last critical areas remaining to finish in the backend service repos is the docker image deployment to the ECR at the end of the travis build. I was hoping to get the details of the ECR deploy documented so that we can finish implementing that piece.

Specifically, the respective backend service repo developers need to know:
1. ECR IP address
2. ECR repo name/namespace
4. docker image name format you are expecting
3. ECR Authentication mechanism or credentials

@MikeTheCanuck had given me the following details before when we were developing/testing some of this functionality:

IP: 845828040396.dkr.ecr.us-west-2.amazonaws.com
Namespace: "production"
Image Name: "disaster-resilience-server"
Authentication: AWS CLI authentication (with AWS_SECRET_KEY=###, AWS_ACCESS_KEY_ID=###, AWS_DEFAULT_REGION="us-west-2")

Are these still valid or is there a different ECR now?

**Comment by MikeTheCanuck** [comment]
They're still valid-ish, though the name of the docker image will vary depending on the way we've coordinated within the docker files and the Travis repo and the Cloud Formation templates.

These are settings I am setting in the Travis Settings on behalf of the project teams as their repos stabilize, so while it's good to document this, it's not necessary for the developers to worry about this.
