### ISSUE TITLE
Create IAM role and policy to enable ECS container tasks to decrypt KMS-encrypted Parameter Store parameter values

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#114]
This is needed to complete #113.

ECS container tasks will need the privilege to read a particular KMS key and use it to decrypt encrypted parameter values in our Parameter Store.

In this blog, "Step 2" outlines a procedure for creating the necessary policies and role:
https://aws.amazon.com/blogs/compute/managing-secrets-for-amazon-ecs-applications-using-parameter-store-and-iam-roles-for-tasks/

There's a few details to decide:
- Role Name to use in `aws iam create-role --role-name ...` command, rather than the example "prod-app1" - perhaps "2018-api-container-kms-decryption", to be self-describing?
- "account ID" specified in the 2nd policy as `<account-id>` - do they mean the ID of the role generated by `aws iam create-role` just above the 2nd policy in that blog, or do they mean the ID of the role of the user creating the policy (since they keep saying "your account ID"?  [I'm sure this is obvious to those folks who trade in AWS IAM all day, but it's sure challenging to follow the implicit assumptions when we're weekend warriors]

There's at least one detail in the specified policies that makes me wonder if they missed a step, and that we'll have to track down the right info:
- the Sid values in the 2nd policy seem awfully specific - are these universal values for this operation, or are they specific to the example that the blogger was working from?  i.e. "Sid": "Stmt1482841904000" and "Sid": "Stmt1482841948000"

**Comment by iant01** [comment]
The account ID would be the Hack Oregon account ID (number) which is 845828040396

The region MUST be replaced with us-west-2, the blog was probably written when SSM was only implemented in us-east and keys are region specific (key created in us-east will not work in us-west.

SID is an optional item (identifier) that can be used to identify different statements in a policy and must be unique in a policy. Most of the time this is left blank. there are some services SQS, SNS that require it.
We would not have to specify it and they can not be used to quiery a statment through the CLI/SDK.

**Comment by MikeTheCanuck** [comment]
Result:
- role name = 2018-api-container-kms-decryption
- account id = 845828040396

**Comment by MikeTheCanuck** [comment]
## Commands to setup role and policies

1. Run this command 
`aws iam create-role --role-name 2018-api-container-kms-decryption --assume-role-policy-document file://ecs-tasks-trust-policy.json`

With the following content as `ecs-tasks-trust-policy.json`:

```
{
   "Version": "2012-10-17",
   "Statement": [
     {
       "Sid": "",
       "Effect": "Allow",
       "Principal": {
         "Service": "ecs-tasks.amazonaws.com"
       },
       "Action": "sts:AssumeRole"
     }
   ]
 }
```

2. Run this command
`aws iam create-policy --policy-name api-container-parameters-access --policy-document file://api-container-parameters-access.json`

With the following content as `api-container-secret-access.json`:

```
{
     "Version": "2012-10-17",
     "Statement": [
         {
             "Effect": "Allow",
             "Action": [
                 "ssm:DescribeParameters"
             ],
             "Resource": "*"
         },
         {
             "Sid": "Stmt1482841904000",
             "Effect": "Allow",
             "Action": [
                 "ssm:GetParameters"
             ],
             "Resource": [
                 "arn:aws:ssm:us-west-2:845828040396:parameter/staging/2018/*",
                 "arn:aws:ssm:us-west-2:845828040396:parameter/production/2018/*"
             ]
         },
         {
             "Sid": "Stmt1482841948000",
             "Effect": "Allow",
             "Action": [
                 "kms:Decrypt"
             ],
             "Resource": [
                 "arn:aws:kms:us-west-2:845828040396:key/0280a59b-d8f5-44e0-8b51-80aec2f27275"
             ]
         }
     ]
 }
```

3. Run the command
`aws iam attach-role-policy --role-name 2018-api-container-kms-decryption --policy-arn "arn:aws:iam::845828040396:policy/api-container-parameters-access"`

**Comment by MikeTheCanuck** [comment]
@DingoEatingFuzz has run these commands; now it's up to us to create the script - [currently here](https://github.com/hackoregon/backend-examplar-2018/blob/parameter-store/bin/get-ssm-parameters.sh) - that will successfully read these values out of SSM and create env vars out of them.

**Comment by MikeTheCanuck** [comment]
https://github.com/hackoregon/hackoregon-aws-infrastructure/issues/66 outlines how we've added this SSM access policy into the CloudFormation template.
