### ISSUE TITLE
Consider removing RAM constraints on API containers

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#115]
One of the problems we've repeatedly grappled with is how much memory do each of the ECS containers require?

## Background

Last year we arbitrarily defaulted all new ECS services to allocate 100 MB of RAM, and only boosted it when we were fairly sure that the application in the container was failing to stay up because it required more RAM than that.

Surveying the ECS services we currently have defined and running (9 of them), we have wild variation in % Memory Utilization at the service level
- from ~80%  max (for HousingService) - which is 80% of 100 MB = 80MB 
- or even ~40% max (for transportService) - which is 40% of 2048 MB = 820MB
- down to ~1.5% max (for Endpoints) - which is 1.5% of 100 MB = 1.5MB

The original thinking behind allocating memory to each service was to ensure we had some control over runaway/leaky applications, and to give us some ability to predict when/if we'd need to grow the size of the underlying EC2 instances (originally and currently **t2.large** with 8GB RAM).

However, in practice we spent a lot more time debugging application startup/health check issues, and while most of those were configuration problems, in at least two cases we found that the applications were consuming well in excess of 100MB just to get to a decent level of performance with a handful of users warming up the API endpoints.

There was almost no time **or expertise** to characterize the memory needs of each Django application - and that expertise (or time) hasn't emerged this year yet either.

At this point we can only imagine how much memory each of the API containers will need allocated, and we could end up wasting days or longer troubleshooting containers until we realize that one's not healthy because it keeps getting terminated by ALB health check because the Django app crashes once it's loaded more data than the allocated memory allows.

## Proposal
We reconfigure the `service.yaml` settings for all of our services to remove the `Memory` allocation from each (which according to Ian, enables ECS EC2-not-Fargate services to be allocated as much or as little memory by ECS/EC2(?) at runtime as they dynamically need.

e.g. remove the `Memory: 100` from this section of the `service.yaml`:

```
TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: budget-service
            ContainerDefinitions:
                - Name: budget-service
                  Essential: true
                  Image: 845828040396.dkr.ecr.us-west-2.amazonaws.com/integration/budget-service
                  Memory: 100
```

## Consequences
This *could* cause more trouble than it solves - especially at the peak loads like we could expect on Demo Day (2018-06-21).  If a number of developers are making last-minute changes *and* hitting APIs hard to test those changes *and* deploying multiple container updates at the same time *and* we try to demo these apps live in front of an audience - AND the sum collection of containers' memory usage exceeds the total 8GB available on the EC2 instance - then we could be in for a very unsuccessful demo.

I don't know how likely this is, and there's a couple of ways we can mitigate that risk:
1. Load up all the containers we have available, then write some basic test script that loads all the frontend pages into a browser at once, then reload those pages a few times each.  Check the total MemoryUtilization at the cluster level here: https://us-west-2.console.aws.amazon.com/ecs/home?region=us-west-2#/clusters
2. If we see we're getting anywhere close to 100% before the demo, we could turn off the 2017 tasks temporarily (especially **transportService**) to free up some memory for the demo - e.g. go to the cluster in ECS, then go into one of the 2017 services, click the **Update** button, then allocate "0" as the **Number of tasks**.

**Comment by znmeb** [comment]
1. I would hope our code cutoff would give DevOps sufficient breathing room to prevent "a number of developers making last minute changes and hitting APIs hard".
2. I haven't seen the RAM requirements for the 2017 containers - is there a document somewhere for those?

**Comment by bhgrant8** [comment]
See this comment for some preliminary work on profiling one API:
https://github.com/hackoregon/civic-devops/issues/104#issuecomment-390385309

Question in that comment is which type of memory we are looking at? `Total` vs `HOT`, also how does cache play into allotment?

From there, we can start to look at some django optimization techniques defined here:
https://docs.djangoproject.com/en/2.0/topics/performance/

Moving the static files generation to the travis build cycle, and turning off migrations in prod should help to mitigate cpu loads for startup. Also making sure apis are not running in DEBUG mode should help mitigate RAM constraints. These maybe changes we want to investigating to backport to last year's projects  on a consistent basis.

**Comment by bhgrant8** [comment]
We may also be able to setup some load-testing using JMeter:
 http://jmeter.apache.org/

**Comment by MikeTheCanuck** [comment]
Ian helpfully pointed out that there are actually three ways to configure memory for an ECS service:
- no memory allocation (as much memory as each service wants)
- specify the `Memory` property - which we do now (container can consume as much memory as it wants to this upper bound, after which point ECS terminates the container)
- specify the `MemoryReservation` property (along with `Memory`) - `MemoryReservation` is a soft target, below the `Memory` hard limit, and can be used to keep well-behaved containers more or less within bounds

e.g. set `MemoryReservation` to 300 MB and `Memory` to 500 MB.  Container can grow anywhere to 500 MB, and if there's memory pressure on the EC2 instance hosting multiple containers, Docker will "attempt to keep the container memory within the limit" (whatever that means), somehow pushing it down to 300 MB where possible.
