### ISSUE TITLE
How to handle Environmental Variables and Secrets in Docker Containers

### ISSUE THREAD

**Issue by bhgrant8** [hackoregon/civic-devops#12]
Last year's strategy to handle both secure settings and those that were needed for basic config were handled in 2-3 places depending on the environment:

1. Local Development - OS and docker config, aws was done through an env.sh script. this script would export the vars to the host system, then these were set in the container through the docker-compose file: https://github.com/hackoregon/backend-service-pattern#1--create-your-environment-file
2. Travis - These same variables were configured in the travis UI when building for ci/cd chain (see settings in travis for one of last year's projects): https://github.com/hackoregon/backend-service-pattern#5-setup-your-project-in-travis

3. Django related settings were set in a project_config.py file and which we manually distributed to devs for local environment, then ran a getconfig script to pull from an s3 bucket in ci/cd chain:
https://github.com/hackoregon/backend-service-pattern/blob/master/bin/getconfig.sh

Questions:
Transportation Systems had experimented with a .env (https://github.com/hackoregon/transportation-system-backend/blob/staging/bin/env.sample) file for holding onto config variables, but ran into an issue with them not being available in the docker-compose - reading through this guide: https://vsupalov.com/docker-arg-env-variable-guide/,  I believe that we are not using the .env as it should in its default way but that it is being handled as an `env_file` as this is how it is declared in the compose, and it is not placed in same directory.

We are going to need to alter our variable strategy, so am opening a ticket here about best practice so we do not have to keep changing it up.

Some considerations:

1. Strategy will need to work in multiple environments, local dev, staging, prod for example
2. Does it make sense to split python config variables into different file, or use single config file?
3. Does the point in the build/run process where the variable is needed affect the strategy?
4. What security implications are there in the strategy we adopt - It is undisputed that there are ways to access environmental variables in a container, and there are real security risks to this - See this issue for example: https://github.com/pydanny/cookiecutter-django/issues/1258
* caveat we are not making use of any public dockerhub/repositories that I am aware so this may be a mitigating factor on the "secrets" question?

Issue on transportation repo for tracking: https://github.com/hackoregon/transportation-system-backend/issues/26

**Comment by znmeb** [comment]
We are using published images as base images for our Dockerfiles. So we definitely need to have a plan to track security issues and other updates to them. We are using at least postgres:10 which in turn uses debian:stretch and gets software from the following repositories:

```
docker run -it --rm postgres:10 /bin/bash
root@80e771049ed4:/# apt update
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://security.debian.org stretch/updates InRelease [63.0 kB]
Get:3 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian stretch Release.gpg [2,434 B]
Get:6 http://deb.debian.org/debian stretch-updates/main amd64 Packages [8,431 B]
Get:7 http://security.debian.org stretch/updates/main amd64 Packages [378 kB]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [9,531 kB]
Get:9 http://apt.postgresql.org/pub/repos/apt stretch-pgdg InRelease [41.3 kB]
Get:10 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64 Packages [193 kB]
Fetched 10.4 MB in 2s (4,584 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
```

We need to do this for every public image we build on ***for deployment*** - we don't for stuff we run on our laptops / workstations. There are others but this is the only one I know well.

**Comment by bhgrant8** [comment]
Transportation Systems has went with the use of a .env file in the root of the directory. it allows us to pass the variables we need into containers through a single file, which could also be set via environmental variables in another environment:

https://docs.docker.com/compose/environment-variables/#the-env-file. I am going to mark this closed from our end.
