### ISSUE TITLE
Replace the SSH private key in the "hacko-integration ECS host" EC2 instances

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#122]
Currently we are unable to SSH into the EC2 instances that host all our ECS containers.

This is because the SSH keys used to initially generate these instances were never distributed to current team members, and are considered MIA.

Replacing these keys means stopping the instances, which is a slightly scary proposition.  We know that the ECS cluster hosted on these instances is recoverable - we've done a recent deploy with the CloudFormation templates used to generate the cluster - but at best there would still be a significant amount of work (that we haven't documented, nor have tried in a year) to rebuild the clusters from fresh EC2 instances.  At worst, there might be some ALB, EIP or other networking trickery to have to recreate.

Ideally though, a stop/start of the instances (with a key update in the middle) would do no more than restart the containers, and would otherwise just be a simple service interruption.

RESULT: we would be able to gather logs from the instances, would be able to interact directly with the docker containers, and would even be able to inspect logs of the apps running in the containers.

**Comment by iant01** [comment]
This issue is a non-issue as the ssh key is accessable now. This issue can be closed.
