### ISSUE TITLE
Confirm new Transportation Systems Project Reqs/Structure

### ISSUE THREAD

**Issue by bhgrant8** [hackoregon/civic-devops#126]
After initial iterations at having separate dbs/api containers (and github repos) for separate microservice apis, it seems this approach is overly complex w/o any real gains ex:

* large RAM overhead for each individual project (300mb x 5 apis? = 1.5gb+)
* multiple small dbs have their own memory needs in database server
* extra env vars to maintain
* more changes to cloud formation.

So while I was away, it looks like the team had already started on creating a combined single database with multiple schema. 

API has been begun here as a single project with multiple tenant apps for individual apis, seems to function fairly well:
https://github.com/znmeb/provisional-transportation-api/tree/znmeb-api-build

will provide the db backup when ready but here are some reqs I'd like to confirm:

* **Database Size**: 5-7gb total
* **Permissions**: Read-only on all schema in database (this varies from the default read-only perms for django apps which maybe for only "public" schema. If unable to assign perms on "all", can provide a list of the specific schema will need perms on.

We will then be able to delete the other databases for our project. 

I will do some initial RAM/memory testing on the api container to confirm that the 300mb estimation for api is still accurate. Otherwise the api project container should function like the examplar in matters related to ops process.

marking as related to: https://github.com/hackoregon/civic-devops/issues/104

**Comment by znmeb** [comment]
1. Yea, the database is in the 5 - 7 GB range when living in the PostGIS server tablespace. It's closer to 5 - 5.25, I think.
2. I have all the code set up on both my laptop and workstation to run cAdvisor; we should load test it.
3. I've added a schema - I'll post the details shortly. This is the origin-destination data from the Census Bureau that covers job counts by residence and work census blocks for 2002 through 2015.

**Comment by bhgrant8** [comment]
As we are deployed and working successfully, I am going to close this out.
