### ISSUE TITLE
Using gevent with gunicorn is throwing a runtime warning

### ISSUE THREAD

**Issue by bhgrant8** [hackoregon/civic-devops#13]
So last year we used gevent asynchronous workers as part of our gunicorn http server for the django api.

Building a test/staging deploy branch of our current api is throwing a runtime warning. Is this a concern?

Branch: https://github.com/hackoregon/transportation-system-backend/tree/gunicorn-setup

Setup that was done: https://github.com/hackoregon/transportation-system-backend/tree/gunicorn-setup#what-was-configured

warning:

```
api_1  | 0 static files copied to '/code/staticfiles', 206 unmodified, 54 post-processed.
api_1  | [2018-02-14 21:02:02 +0000] [9] [INFO] Starting gunicorn 19.7.0
api_1  | [2018-02-14 21:02:02 +0000] [9] [INFO] Listening at: http://0.0.0.0:8000 (9)
api_1  | [2018-02-14 21:02:02 +0000] [9] [INFO] Using worker: gevent
api_1  | [2018-02-14 21:02:02 +0000] [9] [INFO] Server is ready. Spawning workers
api_1  | [2018-02-14 21:02:02 +0000] [12] [INFO] Booting worker with pid: 12
api_1  | [2018-02-14 21:02:02 +0000] [12] [INFO] Worker spawned (pid: 12)
api_1  | /usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py:65: RuntimeWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier.
api_1  |   monkey.patch_all(subprocess=True)
api_1  | [2018-02-14 21:02:02 +0000] [13] [INFO] Booting worker with pid: 13
api_1  | [2018-02-14 21:02:02 +0000] [13] [INFO] Worker spawned (pid: 13)
api_1  | /usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py:65: RuntimeWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier.
api_1  |   monkey.patch_all(subprocess=True)
api_1  | [2018-02-14 21:02:02 +0000] [16] [INFO] Booting worker with pid: 16
api_1  | [2018-02-14 21:02:02 +0000] [16] [INFO] Worker spawned (pid: 16)
api_1  | [2018-02-14 21:02:02 +0000] [17] [INFO] Booting worker with pid: 17
api_1  | [2018-02-14 21:02:02 +0000] [17] [INFO] Worker spawned (pid: 17)
api_1  | /usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py:65: RuntimeWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier.
api_1  |   monkey.patch_all(subprocess=True)
api_1  | /usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py:65: RuntimeWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier.
api_1  |   monkey.patch_all(subprocess=True)
```

Note: I am not doing anything special to monkey patch the process, this should happen automagically for gunicorn/gevent/django setup:
http://docs.gunicorn.org/en/latest/design.html#async-workers

**Comment by MikeTheCanuck** [comment]
Looks like you're hitting this recently-added warning:
https://github.com/gevent/gevent/commit/3eb826c66c8b9f3fba6e3c6e3943d0b44b7bd336

Which was originally implemented due to this issue:
https://github.com/gevent/gevent/issues/1016

I don't remember how we implemented "monkey patching earlier" if at all last season, but I recall at least running into these kinds of discussions and wondering if there *was* something non-default we could do when using `gevent`.

[This article](http://www.gevent.org/gevent.monkey.html#patching) states, "Some frameworks, such as gunicorn, handle monkey-patching for you. Check their documentation to be sure."

(Note: the `gunicorn` project cross-referenced this issue 8 days ago here: https://github.com/benoitc/gunicorn/issues/1566 - where he mentioned "Basically, importing requests and then monkey-patching was essentially guaranteed to lead to a RecursionError")

So I headed over to Google and ended up with a couple of possibly-unrelated ideas:
1. https://stackoverflow.com/questions/11999962/which-features-are-monkey-patched-by-gunicorn-gevent-worker#12012841
"You can still call your own initialization code when your app boots."
"First, the gunicorn use SyncWorkers as default and if you don't change the configuration, then the server won't use greenlets. And even though you monkey patch all, I think it doesn't have much help because gunicorn handles one request at a time as default."
2. An interesting `gist` to implement a `gunicorn.conf` which I don't remember experimenting with last year:
https://gist.github.com/jaddison/4506070

@bhgrant8 and @leobender - can either of you look into these leads one at a time and report back if any of them look promising/feasible?

**Comment by bhgrant8** [comment]
Emergency response did make use of a gunicorn_conf.py last project season: 
https://github.com/hackoregon/emergency-response-backend/blob/master/gunicorn_config.py

based on the example_config provided by gunicorn project:
https://github.com/benoitc/gunicorn/blob/master/examples/example_config.py

If nothing else, the pre/post fork functions allow for some additional logging, useful for troubleshooting. The gist provided is using an outdated package: `gevent_psycopg2`, new version of this is `psycogreen` and gevent is a module within so experiemented with this following code:

```

try:
    # fail 'successfully' if either of these modules aren't installed
    from gevent import monkey
    from psycogreen.gevent import patch_psycopg


    # setting this inside the 'try' ensures that we only
    # activate the gevent worker pool if we have gevent installed
    worker_class = 'gevent'

    # this ensures forked processes are patched with gevent/gevent-psycopg2
    def do_post_fork(server, worker):
        monkey.patch_all()
        gevent_psycopg2.monkey_patch()

        # you should see this text in your gunicorn logs if it was successful
        worker.log.info("Made Psycopg2 Green")

    post_fork = do_post_fork
except ImportError:
    pass
```

in my gunicorn_config.py.

still receiving warning.:

```
api_1  |   Your models have changes that are not yet reflected in a migration, and so won't be applied.
api_1  |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
api_1  | [2018-02-18 20:32:50 +0000] [21] [INFO] Starting gunicorn 19.7.0
api_1  | [2018-02-18 20:32:50 +0000] [21] [INFO] Listening at: http://0.0.0.0:8000 (21)
api_1  | [2018-02-18 20:32:50 +0000] [21] [INFO] Using worker: gevent
api_1  | [2018-02-18 20:32:50 +0000] [21] [INFO] Server is ready. Spawning workers
api_1  | [2018-02-18 20:32:50 +0000] [24] [INFO] Booting worker with pid: 24
api_1  | gunicorn_config.py:82: RuntimeWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier.
api_1  |   monkey.patch_all()
api_1  | [2018-02-18 20:32:50 +0000] [24] [INFO] Made Psycopg2 Green
api_1  | [2018-02-18 20:32:51 +0000] [25] [INFO] Booting worker with pid: 25
api_1  | gunicorn_config.py:82: RuntimeWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier.
api_1  |   monkey.patch_all()
api_1  | [2018-02-18 20:32:51 +0000] [25] [INFO] Made Psycopg2 Green
api_1  | [2018-02-18 20:32:51 +0000] [27] [INFO] Booting worker with pid: 27
api_1  | [2018-02-18 20:32:51 +0000] [28] [INFO] Booting worker with pid: 28
api_1  | gunicorn_config.py:82: RuntimeWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier.
api_1  |   monkey.patch_all()
api_1  | [2018-02-18 20:32:51 +0000] [27] [INFO] Made Psycopg2 Green
api_1  | gunicorn_config.py:82: RuntimeWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier.
api_1  |   monkey.patch_all()
api_1  | [2018-02-18 20:32:51 +0000] [28] [INFO] Made Psycopg2 Green
```

I do wonder about using a post_fork hook though for a warning about patching earlier?

**Comment by MikeTheCanuck** [comment]
Thanks for ref to your `_conf` experiment.

The `psycogreen`, yes. 

If this is really just a warning with no crashing, I’d support moving forward as-is knowing we’ve doc’d some ideas here. I don’t believe there’s any SSL/TLS interactions at this level of our infrastructure (but I’ve been wrong on assumptions like this). Better for us to find out sooner than later.

**Comment by bhgrant8** [comment]
Thanks for the input. We are currently moving forward as is and will report any problems, if they come up. This might be a warning though to get some systems/load-testing strategies once we go live.

**Comment by nilinykh** [comment]
Is there any update on this issue regarding the possible solution?
Experiencing the same issue when using `geventwebsocket.gunicorn.workers.GeventWebSocketWorker` worker,  gives the same warning.
