### ISSUE TITLE
docker push gets Permission denied

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#141]
Brian ran into this on Transportation-Systems-backend-2018, and now @hassanshamim  is hitting this on neighborhoods-2018:

```
$ bin/deploy.sh
Getting the ECR login...
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
Running docker push command...
invalid reference format
bin/deploy.sh: line 20: bin/ecs-deploy.sh: Permission denied
```
@BrianHGrant What did you do to fix this?

**Comment by MikeTheCanuck** [comment]
Solution from Brian's lips to god's ear:
run `chmod +x /bin/*.sh`

**Comment by hassanshamim** [comment]
should be:
`chmod +x ./bin/*.sh`  to update the project's `bin` directory and not your root `bin`
