### ISSUE TITLE
Any needs to throttle/rate limit on the django level?

### ISSUE THREAD

**Issue by BrianHGrant** [hackoregon/civic-devops#15]
@kiniadit who has been working on django/api development for transportation-systems asked at our team meeting if there were any needs to handle throttling or rate limiting of requests within the django app.

I do not have much background on how this works in django, so he would be the one to answer further questions on this end.

A consideration would also be how this may be able to be handled at an ingress level within aws which would be a cross project solution, maybe more sustainable then implementing code in individual projects.

**Comment by MikeTheCanuck** [comment]
Great question, thanks for raising it.

Many publically-accessible systems eventually encounter traffic patterns that require countermeasures such as throttling, rate-limiting and API keys.

Hack Oregon aspires to be one of those systems and I am hopeful we will get there one day. However, at present the evidence and traffic patterns are clearly well short of requiring such countermeasures. 

I’m going to implement a priority labelling system to clarify where in our priorities our issues lie. We can consider this something to address in the future, but is anything but urgent compared to the other issues we face at present.

**Comment by bhgrant8** [comment]
Sounds good, figured wasn't too high on our radar. 

Nothing we do is mission critical so our DOS attack/cost mitigation strategy could be just shut it down and figure out what's up.

**Comment by kiniadit** [comment]
agreed that isn't critical and probably better done [globally](https://aws.amazon.com/blogs/aws/protect-web-sites-services-using-rate-based-rules-for-aws-waf/). definitely brings to mind [YagNi](http://wiki.c2.com/?YouArentGonnaNeedIt) ;)

that being said, rate limit throttling is fairly straightforward to implement on Django.
