### ISSUE TITLE
Define structure for Transportation Systems Project and APIs

### ISSUE THREAD

**Issue by BrianHGrant** [hackoregon/civic-devops#16]
This is a continuation of a discussion within the Transportation Systems Team but priority has been raised as we begin to move towards API development of our second dataset. 

Background:

* We have multiple datasets which are being deployed as individual apis within the transportation-systems project.  
* While we can essentially hack a single django project to accomodate multiple, non-related APIs, the preference would be to develop in separate, containerized services with repos. 
* We are taking into consideration the organizational consideration on reducing number of repos, and working to combine and archive data ingestion/data science repos
* It is far easier to combine multiple Django projects into one then separate them.
* Our api developer is starting work on the API for the next data set, which will be on his personal repo temporarily until a decision is made. This makes collaboration difficult.
* Our project discussion: https://github.com/hackoregon/transportation-system-backend/issues/12
#
Question:

Does working with a single repo/django project per api/dataset work from an organizational perspective with the consideration that we will be decreasing the number of overall repos for our team?

**Comment by MikeTheCanuck** [comment]
The question of single repo vs multiple repo is one that is being fielded by @DingoEatingFuzz and I’d like him to weigh in before we dive into the technical details.  Michael, is this an acceptable way to organise T-S’s APIs, or do you have a different approach?

**Comment by DingoEatingFuzz** [comment]
> Does working with a single repo/django project per api/dataset work from an organizational perspective with the consideration that we will be decreasing the number of overall repos for our team?

The biggest consideration when determining when you should separate projects to different repos is CI/CD. 

To this end, if these are separate APIs, separately containerized, then it makes sense to make them separate repos with individual travis configurations for continuous delivery.

> The question of single repo vs multiple repo is one that is being fielded by @DingoEatingFuzz and I’d like him to weigh in before we dive into the technical details.

It's also worth mentioning that one of the major reasons a monorepo makes sense for https://github.com/hackoregon/civic is the existing tooling [Lerna](https://lernajs.io/), which is specifically for JavaScript projects.

**Comment by MikeTheCanuck** [comment]
That said, the CI/CD for individual packages in a Monorepo is still TBD, as would be the same question mark if a monorepo of APIs had to be deployed individually.

**Comment by bhgrant8** [comment]
Sounds like we are ok with moving forward with separate repos at this time, unless something radically changes with our CI/CD pipeline.

**Comment by DingoEatingFuzz** [comment]
Sounds good.
