### ISSUE TITLE
Document the checklist of files and infrastructure to change when bringing a new ECS service online

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#160]
We need a checklist of all the places to make changes for a new ECS/CloudFormation service, before we all forget again for another year.

There's a number of pieces of infrastructure to change:
- `service.yaml` - add a new folder and file for the new service
- `master.yaml` - add a new section under **Resources** and **Output**
- ALB - create a new Target Group (somehow??? - or is this done automatically by CloudFormation?)
- Route 53 - only if we're also standing up a new subdomain to support the new service(s)

What else?

**Comment by iant01** [comment]
ALB and target groups are handled auto magically by adding making the master.yaml and adding the service service.yaml file
