### ISSUE TITLE
Add ECS volume setting to cloudformation

### ISSUE THREAD

**Issue by iant01** [hackoregon/civic-devops#164]
Currently when the ecs volume size is changed manually, if the instance is replaced due to and update or an instance dies or is manually stopped, the volume changes are lost. Adding the setting to the instance launch configuration enables a central place to make the change, cause it to be pushed out by autoscaler and makes sure that if an instance is replaced it has the same volume size and does not return to the default 22 GB size.

**Comment by iant01** [comment]
merge/pull 37 submitted.

**Comment by MikeTheCanuck** [comment]
Presume you meant to link to this PR
https://github.com/hackoregon/hackoregon-aws-infrastructure/pull/37
