### ISSUE TITLE
Enable PostgreSQL databases for all Project teams

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#18]
Medium-term Plan: migrate all PostgreSQL instances from separate EC2 machines to a single large/XL machine.

## Short-term plan
- [x] Create EC2 VM for Developer data layer (separate from production)
- [x] Install new PostgreSQL server (9.6.latest) in the new VM (name includes "dev" to communicate its role)
- [x] Create new database instances for each current project team
- [x] Create unique credentials for each database instance
- [x] Communicate database IP, name, instance names and credentials for each database instance to each team's data manager

## Project teams online
- [x] disaster-resilience
- [x] housing-affordability
- [x] local-elections
- [x] neighborhood-development
- [x] transportation-systems

**Comment by znmeb** [comment]
Many Transportation Systems projects? So far it's just three, and two of them are small. The other one looks like it's bigger than anything Hack Oregon's ever done. ;-)

**Comment by MikeTheCanuck** [comment]
PRs #23, #24, #26 and #29 enable us to automatically build and configure PostgreSQL on an EC2 machine instance with an external EBS data volume.
