### ISSUE TITLE
Update Travis ECS_SERVICE_NAME env vars for all legacy services, to re-enable deploy pipeline

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#184]
Due to an unintentional but complete redeploy of the ECS cluster, all the service names got updated.

The service names were updated in the corresponding Travis repos' ECS_SERVICE_NAME environment variables, but only for the 2018 repos.

The remaining repos include:
- [x] [team-budget](https://travis-ci.org/hackoregon/team-budget)
- [x] [emergency-response-backend](https://travis-ci.org/hackoregon/emergency-response-backend/settings)
- [x] [teamHomelessness](https://travis-ci.org/hackoregon/teamHomelessness/settings)
- [x] [housing-backend](https://travis-ci.org/hackoregon/housing-backend)
- [x] [transportation-backend](https://travis-ci.org/hackoregon/transportation-backend/settings)
- [x] [endpoint-service-catalog](https://travis-ci.org/hackoregon/endpoint-service-catalog/settings)
- [ ] civic-lab-service (note: there *is* no such GitHub repo, this sucker must've been manually deployed)

**Comment by nam20485** [comment]
What about me? (Disaster-resilience)

**Comment by MikeTheCanuck** [comment]
I am under the impression that all the 2018 container services (all the stuff from Civic, as well as the 5 Django app repos) were updated in Travis already.  If you repo is not yet updated, then you'll see that the deploy step of the Travis build is no longer finishing with these steps:

```
Using image name: 845828040396.dkr.ecr.us-west-2.amazonaws.com/production/[secure]-service:latest
Current task definition: arn:aws:ecs:us-west-2:845828040396:task-definition/[secure]-service:52
New task definition: arn:aws:ecs:us-west-2:845828040396:task-definition/[secure]-service:53
Service updated successfully, new task definition running.
```

Checking the [latest merge-to-master build for Disaster Resilience](https://travis-ci.org/hackoregon/disaster-resilience-backend/jobs/394832060#L1395), this is exactly what's happening - so looks like that Travis repo was updated already.

**Comment by MikeTheCanuck** [comment]
Fixed all the 2017 Travis repos.
