### ISSUE TITLE
PostgreSQL - have not been able to automate init with non-default data directory

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#20]
PROBLEM STATEMENT: I want to fully script the installation and configuration of PostgreSQL, such that it only ever uses a non-default data directory to store all databases.  The intent is to perform this installation in AWS on an EC2 virtual machine to which we've attached an external storage volume (to persist the database files, and to simplify snapshot and backup operations).  The goal is to enable us to "snapshot" the external volume and treat that as a working backup of data, such that restoring the snapshots to a restored, empty database server should bring the databases back online in seconds.

I've spent the morning trying to build a repeatable script for installing and configuring PostgreSQL to use a non-default data directory.  PostgreSQL appear to have deprecated a number of the well-documented methods for initializing PostgreSQL with a non-default data directory, and I'm at wit's end trying to thread this needle.

Prerequisites: create and `sudo chown postgres ...` a new directory on the filesystem where database data files will be stored (e.g. `/data/databases`)

Many documentation start out with a command like the following:
```
sudo service postgresql initdb --pgdata=/data/databases
```

However, this doesn't actually change the directory where the database cluster is stored
```
$ sudo service postgresql initdb --pgdata=/data/databases
Hint: the preferred way to do this is now "/usr/bin/postgresql-setup --initdb --unit postgresql"
 * Initializing database in '/var/lib/pgsql/data'
 * Initialized, logs are in /var/lib/pgsql/initdb_postgresql.log
```
And when I `ls` the `/data/databases` directory it still empty (all expected files are instead found in `/var/lib/pgsql/data/`).

When I explore the recommended `postgresql-setup` command, there's no official docs on it, and what's embedded in the on-disk README doesn't support any sort of `data` parameter, only `initdb` and `unit`.

Other docs recommend the more up-to-date option is using the `initdb` executable that ships with PostgreSQL - but not only do the PostgreSQL docs warn away from directly calling `initdb` anymore, but also when it's used like `#sudo -u postgres initdb --pgdata=$DATA_DIRECTORY`, then later when you run `sudo service postgresql start` that will error out, ultimately due to an error 'Directory "/var/lib/pgsql/data" is missing or empty.'

Other indications [tell me to use](https://www.mankier.com/1/postgresql-new-systemd-unit) the `postgresql-new-systemd-unit` command which is also thinly-documented.  While this has a `--datadir` parameter, it also is intended for creating a second, non-default database cluster on an existing server - not for configuring the default cluster.

Finally, there are various techniques people have documented [e.g.
 this](http://www.whiteboardcoder.com/2012/04/change-postgres-datadirectory-folder.html) or [maybe this](https://www.postgresql.org/message-id/000901c5106c$47be3f90$797ba8c0@jfradkin) over the years to manually override the default `/var/lib/pgsql/data` directory, using `PGDATA` env var, or editing the `postgressql.conf` files.  The former seems ripe for errors, and the latter is a bitch to automate (editing an existing line of text in a file).

I've read through a dozen or more [troubleshooting articles](https://serverfault.com/questions/350045/postgresql-service-initdb-doesnt-work), but I end up feeling like they're not really addressing the should-be-standardized-and-well-documented-but-isn't scenario of automating the build of a PostgreSQL server that only ever stores its data off the root disk.

Current unstable script that I've been working on is here:
https://github.com/hackoregon/civic-devops/blob/database-script/bin/create-database-development.sh

**Comment by znmeb** [comment]
So you want to run `su - postgres -c "initdb -D /some/path/on/the/hard/drive"` and that doesn't work?

**Comment by MikeTheCanuck** [comment]
```
$ su postgres -c "initdb -D /databases"
Password: 
su: Authentication failure
```
(I don't have a password set for `postgres` OS user, nor do I want to.)

```
$ sudo -u postgres -c "initdb -D /databases"
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-u user] file ...
```
(This fails for reasons my exhausted brain doesn't get right now.)

**Comment by MikeTheCanuck** [comment]
@znmeb Could you spell out the command sequence that would accomplish "let it put the maintenance database and all the config files in the default place and use PostgreSQL tablespaces for the big databases"?  I've been up all night on this and can't think straight right now.

(note: `su -` is not an option here, as I note above)

**Comment by znmeb** [comment]
The steps are:
1. Install PostgreSQL with all the defaults.
2. Attach additional hard drives for your data and format them as root, or make sure your root drive is big enough and format your data partitions there. I like the multiple drive version because more IOPS are available.
3. Create tablespaces on the new partitions: https://www.postgresql.org/docs/9.6/static/manage-ag-tablespaces.html
4, Create databases in the tablespaces.

You'll need `root` for a lot of this and you'll need to do some `chown -R postgres:postgres` operations to make things work.

**Comment by MikeTheCanuck** [comment]
If I take a copy of the tablespaces directory while the database server is stopped (effectively what AWS "snapshot" does), is there data is the root volume that's necessary to re-mount the tables as a database?  e.g. is the database' schema stored in the root volume, and the data pages in the tablespace directory?  Or could I rebuild a new database from code (following the same three-step procedure above) and mount a copy of the tablespaces "snapshot" as a quick recovery/migration of the data?

Snapshots are a helluva lot faster than backups and are the preferred strategy for having up-to-date copies of the data (with occasional e.g. weekly backups for belt-and-suspenders coverage).

**Comment by znmeb** [comment]
Read the Tablespaces document I linked to carefully. Once you define a tablespace, PostgreSQL manages it and you don't touch it! Otherwise data will be lost.

**Comment by MikeTheCanuck** [comment]
@znmeb I've read the document twice and it still doesn't explicitly answer my question.

**Comment by MikeTheCanuck** [comment]
Continuing down the non-tablespaces route, since that doesn't seem to meet our current requirements:
- having built the server with [this partially-working script](https://github.com/hackoregon/civic-devops/blob/database-script/bin/create-database-development.sh) which still fails at line 25, I still end up with a server that responds like this when I launch the `psql` command:
```shell
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```
- I found [this article] which gave me the clue that perhaps I should `sudo chmod 700 /databases` to make the permissions on the data directory only accessible to `postgres` user.  Reboot the server, but `psql` still reports the same error
- that article also talked about the directory needing be be owned by user `postgres` AND group `postgres` - It was previously owned by `postgres:root` so I ran `sudo chown -R postgres:postgres /databases` but still no dice.
- but wait, I forgot that when I reboot the server I have to restart the daemon, because I haven't made that persistent yet - so this is how the naked server starts:
```shell
$ sudo service postgresql status
Redirecting to /bin/systemctl status postgresql.service
● postgresql.service - PostgreSQL database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
```
- and after running `sudo postgresql service start`, the sucker reports:
```
Redirecting to /bin/systemctl start postgresql.service
Job for postgresql.service failed because the control process exited with error code. See "systemctl status postgresql.service" and "journalctl -xe" for details.
```
- so I run `systemctl status postgresql.service -l` and it says
```shell
● postgresql.service - PostgreSQL database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2018-03-01 05:41:09 UTC; 2min 8s ago
  Process: 3196 ExecStartPre=/usr/libexec/postgresql-check-db-dir %N (code=exited, status=1/FAILURE)

Mar 01 05:41:09 ip-172-31-31-191.us-west-2.compute.internal systemd[1]: Starting PostgreSQL database server...
Mar 01 05:41:09 ip-172-31-31-191.us-west-2.compute.internal postgresql-check-db-dir[3196]: Directory "/var/lib/pgsql/data" is missing or empty.
Mar 01 05:41:09 ip-172-31-31-191.us-west-2.compute.internal postgresql-check-db-dir[3196]: Use "/usr/bin/postgresql-setup --initdb"
Mar 01 05:41:09 ip-172-31-31-191.us-west-2.compute.internal postgresql-check-db-dir[3196]: to initialize the database cluster.
Mar 01 05:41:09 ip-172-31-31-191.us-west-2.compute.internal postgresql-check-db-dir[3196]: See /usr/share/doc/postgresql-9.6.6/README.rpm-dist for more information.
Mar 01 05:41:09 ip-172-31-31-191.us-west-2.compute.internal systemd[1]: postgresql.service: control process exited, code=exited status=1
Mar 01 05:41:09 ip-172-31-31-191.us-west-2.compute.internal systemd[1]: Failed to start PostgreSQL database server.
Mar 01 05:41:09 ip-172-31-31-191.us-west-2.compute.internal systemd[1]: Unit postgresql.service entered failed state.
Mar 01 05:41:09 ip-172-31-31-191.us-west-2.compute.internal systemd[1]: postgresql.service failed.
```
- and when I run `sudo ls -la /var/lib/pgsql/data` it reports:
```shell
total 0
drwx------ 2 postgres postgres  6 Dec 11 21:42 .
drwx------ 4 postgres postgres 54 Feb 25 21:38 ..
```

So, now when I run my `create-database-development.sh` script, it fails at line 18 with:
```shell
LOCATION:  resolve_symlinks, exec.c:293
FATAL:  -c initdb -D /databases requires a value
```

**Comment by MikeTheCanuck** [comment]
Searching on the various unique strings of the errors we're seeing, I found two things:
1. multiple references to getting out of a home directory when launching a `sudo` command
2. [this article]() which caused me to slightly change the command in line 18

This results in some measure of success, which I haven't seen for a while:
```shell
sudo su - postgres postgres -c "initdb -D $DATA_DIRECTORY"
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /databases ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /databases -l logfile start
```

However, the next step still fails:
```shell
$ sudo service postgresql start
Redirecting to /bin/systemctl start postgresql.service
Job for postgresql.service failed because the control process exited with error code. See "systemctl status postgresql.service" and "journalctl -xe" for details.
```

And then this output:
```shell
$ systemctl status postgresql.service -l
● postgresql.service - PostgreSQL database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2018-03-01 06:19:18 UTC; 4min 39s ago
  Process: 11867 ExecStartPre=/usr/libexec/postgresql-check-db-dir %N (code=exited, status=1/FAILURE)

Mar 01 06:19:18 ip-172-31-30-179.us-west-2.compute.internal systemd[1]: Starting PostgreSQL database server...
Mar 01 06:19:18 ip-172-31-30-179.us-west-2.compute.internal postgresql-check-db-dir[11867]: Directory "/var/lib/pgsql/data" is missing or empty.
Mar 01 06:19:18 ip-172-31-30-179.us-west-2.compute.internal postgresql-check-db-dir[11867]: Use "/usr/bin/postgresql-setup --initdb"
Mar 01 06:19:18 ip-172-31-30-179.us-west-2.compute.internal postgresql-check-db-dir[11867]: to initialize the database cluster.
Mar 01 06:19:18 ip-172-31-30-179.us-west-2.compute.internal postgresql-check-db-dir[11867]: See /usr/share/doc/postgresql-9.6.6/README.rpm-dist for more information.
Mar 01 06:19:18 ip-172-31-30-179.us-west-2.compute.internal systemd[1]: postgresql.service: control process exited, code=exited status=1
Mar 01 06:19:18 ip-172-31-30-179.us-west-2.compute.internal systemd[1]: Failed to start PostgreSQL database server.
Mar 01 06:19:18 ip-172-31-30-179.us-west-2.compute.internal systemd[1]: Unit postgresql.service entered failed state.
Mar 01 06:19:18 ip-172-31-30-179.us-west-2.compute.internal systemd[1]: postgresql.service failed.
```

And...
```shell
$ sudo ls -la /var/lib/pgsql/data
total 0
drwx------ 2 postgres postgres  6 Dec 11 21:42 .
drwx------ 4 postgres postgres 54 Mar  1 05:58 ..
```

And...
```shell
$ sudo ls -la /databases
total 52
drwx------ 19 postgres postgres  4096 Mar  1 06:18 .
dr-xr-xr-x 19 root     root       274 Mar  1 05:58 ..
drwx------  5 postgres postgres    41 Mar  1 06:18 base
drwx------  2 postgres postgres  4096 Mar  1 06:18 global
drwx------  2 postgres postgres    18 Mar  1 06:18 pg_clog
drwx------  2 postgres postgres     6 Mar  1 06:18 pg_commit_ts
drwx------  2 postgres postgres     6 Mar  1 06:18 pg_dynshmem
-rw-------  1 postgres postgres  4468 Mar  1 06:18 pg_hba.conf
-rw-------  1 postgres postgres  1636 Mar  1 06:18 pg_ident.conf
drwx------  4 postgres postgres    39 Mar  1 06:18 pg_logical
drwx------  4 postgres postgres    36 Mar  1 06:18 pg_multixact
drwx------  2 postgres postgres    18 Mar  1 06:18 pg_notify
drwx------  2 postgres postgres     6 Mar  1 06:18 pg_replslot
drwx------  2 postgres postgres     6 Mar  1 06:18 pg_serial
drwx------  2 postgres postgres     6 Mar  1 06:18 pg_snapshots
drwx------  2 postgres postgres     6 Mar  1 06:18 pg_stat
drwx------  2 postgres postgres     6 Mar  1 06:18 pg_stat_tmp
drwx------  2 postgres postgres    18 Mar  1 06:18 pg_subtrans
drwx------  2 postgres postgres     6 Mar  1 06:18 pg_tblspc
drwx------  2 postgres postgres     6 Mar  1 06:18 pg_twophase
-rw-------  1 postgres postgres     4 Mar  1 06:18 PG_VERSION
drwx------  3 postgres postgres    60 Mar  1 06:18 pg_xlog
-rw-------  1 postgres postgres    88 Mar  1 06:18 postgresql.auto.conf
-rw-------  1 postgres postgres 22301 Mar  1 06:18 postgresql.conf
```

**Comment by MikeTheCanuck** [comment]
Well, after another stretch of exhausting searches for clues, I *did* turn up this procedure which definitely mirrors what we're trying to do with a separate EBS volume on which to store the database files:
https://www.migrate2cloud.com/blog/postgresql-on-ec2/

It requires editing `/etc/init.d/postgresql` which isn't something I'm comfortable trying to do from a script, but at least it proves that this *is* possible (if not using the approach I've been trying).

**Comment by MikeTheCanuck** [comment]
ALERT: success is imminent.  The *pgsql-admin* mailing list was a wealth of specific, useful information, and I'm testing out the details of the rest of the build right now.

**Comment by znmeb** [comment]
Awesome! Ian and I were talking about that this afternoon.

**Comment by MikeTheCanuck** [comment]
This thread I started on *pgsql-admin* led to two very informative responses:
https://www.postgresql.org/message-id/CAEzHCEPibAGQSomzGHSr5M0VKD36v4jpPtwO6SppNpzE6FT%3DyQ%40mail.gmail.com

This article is the key to initializing PostgreSQL 9.6 (and apparently 10.x) with a non-default `data_directory` to house the default database cluster:
https://pgstef.github.io/2018/02/28/custom_pgdata_with_systemd.html

As of commit 364fb7f15253081e3a1376ad61b4020964c27573, this issue is resolved.
