### ISSUE TITLE
Initial setup and evaluation of Prometheus for EC2 monitoring

### ISSUE THREAD

**Issue by danieldn** [hackoregon/civic-devops#226]
**Summary**

The purpose of this story is to evaluate Prometheus as a monitoring solution. We want developers to monitor EC2 instances without going through the AWS console. The ideal solution should expose monitoring of all DBs and APIs. This evaluation should done against current CIVIC infra resources. It should also consider the future state of CIVIC as the platform expands and new features added (e.g. automatic service discovery and automatic monitoring of those services). The scope of this story should be limited to demonstrating Prometheus against a subset of CIVIC resources on AWS. It does not need to be a complete implementation.
 
**Impact**

T2: Expose monitoring of all DBs and APIs

**Tasks**
- [ ] Understand how Prometheus works, how it's installed, common configurations, and common use cases
- [ ] Deploy Prometheus (docker container on ECS?) and show monitoring for one EC2 instance (what will be exposed?)
- [ ] TBD

**Definition of Done**

Demonstrate Prometheus deployed on AWS and monitoring some EC2 instance (DB would be a plus). Capture the configuration and show how it can scale. Show how an end user can connect from their machine to the Prometheus setup.

**Comment by radmosley** [comment]
Determined that a broader scope of tools will be needed to accomplish our monitoring goals.
