### ISSUE TITLE
Request: Postgres instance and s3 access for transportation team

### ISSUE THREAD

**Issue by danieldn** [hackoregon/civic-devops#229]
**Summary**
See https://docs.google.com/document/d/1L6WcZI_fOiT2R7QzNz57nTfPTSUcNpty6pfd2sPcMh4/edit#

**Impact**

Resource request

**Tasks**
- [ ] TBD

**Definition of Done**

Approved developers of transportation team shall have access to s3 and postgres to complete their cards.

**Comment by MikeTheCanuck** [comment]
Manual RDS installation for now to workaround our CloudFormation testing problems:

- Use case: dev/test (non-replicated)
- DB engine: PostgreSQL 11.2-R1
- DB instance class: db.t2.small
- Allocated storage: 60GB
- VPC security groups: hacko-public-database
- log exports: Postgresql logs published to CloudWatch
- Enable deletion protection
- Endpoint address: transportation-2019.caicgny9d8nv.us-west-2.rds.amazonaws.com
All other settings at default.

SQL credentials will be distributed directly.

**Comment by MikeTheCanuck** [comment]
The login role for this RDS instance has the following privileges:
- Can login
- Create databases
- Inherit rights from the parent roles

**Comment by MikeTheCanuck** [comment]
Post-creation configuration steps:
- add PostGIS support: login through PGAdmin, browse to Databases > postgres > Extensions, right-click, choose Create > Extension, select `postgis` from the Name box and hit Save
