### ISSUE TITLE
Request: Housing RDS Instance

### ISSUE THREAD

**Issue by danieldn** [hackoregon/civic-devops#230]
Instructions: Replace text below with details corresponding to your story

**Summary**

https://docs.google.com/document/d/1vHR-fTfgaILh2V2LkshEEnfOSG6f5DL7CKjeiERHarM/edit

**Impact**

**Tasks**

**Definition of Done**

**Comment by MikeTheCanuck** [comment]
Manual RDS installation for now to workaround our CloudFormation testing problems:

DB instance identifier: housing-2019-staging
Use case: dev/test (non-replicated)
DB engine: PostgreSQL 11.2-R1
DB instance class: db.t2.small
Allocated storage: 60GB (complete guess - it's impossible to predict how much space a 7.5GB dump will actually need)
VPC: public-database
VPC security groups: hacko-public-database
log exports: Postgresql logs published to CloudWatch
Enable deletion protection
Endpoint address: housing-2019-staging.caicgny9d8nv.us-west-2.rds.amazonaws.com
All other settings at default.
SQL credentials will be distributed directly.

**Comment by MikeTheCanuck** [comment]
The login role for this RDS instance has the following privileges:

- Can login
- Create databases
- Inherit rights from the parent roles

**Comment by MikeTheCanuck** [comment]
Post-creation configuration steps:

- create application login role
- add PostGIS support: login through PGAdmin, browse to Databases > postgres > Extensions, right-click, choose Create > Extension, select postgis from the Name box and hit Save

**Comment by danieldn** [comment]
Reopening.

Communicate to housing how to populate RDS instance from jumpbox

**Comment by MikeTheCanuck** [comment]
@danieldn can you remind me who is the point of contact for the Housing team - i.e. to whom will I send the PEM file, username/password and instructions?

**Comment by MikeTheCanuck** [comment]
I see that I've already passed along the connectivity info to @nickembrey a few weeks back.

Nick, don't forget that if you want to do a large database restore you can take advantage of the jumpbox that we host in AWS for this purpose:
https://github.com/hackoregon/civic-devops/blob/master/docs/database/2019/HOWTO:%20Use%20jumpbox%20to%20restore%20PostgreSQL%20from%20S3.md

If you need access to it, please let me know and I'll pass along the `.pem` file that gives you SSH access to it.
