### ISSUE TITLE
Legacy Fargate tasks not authorized to perform ssm:GetParameters

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#252]
Something isn't right with our two previously-working Fargate deployments recently - both are suffering this kind of error on redeploy:

```
An error occurred (AccessDeniedException) when calling the GetParameters operation: User: arn:aws:sts::845828040396:assumed-role/ecs-service-hacko-integration-2017Emergency-1OUW82E58RBC1/047bdf30-0a11-4fa5-a26e-29beb6005c60 is not authorized to perform: ssm:GetParameters on resource: arn:aws:ssm:us-west-2:845828040396:parameter/production/2017/API/emergency-service/POSTGRES_PASSWORD
```

I've tried this a few times over a few days and it's failing consistently like this.

I had thought we'd granted access to the SSM parameters of interest in some form or fashion, but apparently not.

So I've added `arn:aws:ssm:us-west-2:845828040396:parameter/production/2017/*` to the `ssm-access` portion of the `ecs-cluster.yaml` template in the https://github.com/hackoregon/hackoregon-aws-infrastructure/ repo and I'll try the deploy again, once the current deploy times out (sadly, this particular failure mode causes the cluster deploy to try for a LONG time to create the task resource, until it finally times out).

**Comment by MikeTheCanuck** [comment]
Oh - looks like the swap to the `/production/2017/` SSM namespace only happened 12 days ago, so my first failure on July 7th must have been the first time I tried a stack deploy since this code change occurred.

**Comment by DingoEatingFuzz** [comment]
Is this still an issue? I too ran into this awhile back, but I thought I had fixed it with this commit: https://github.com/hackoregon/hackoregon-aws-infrastructure/commit/b794b6ccae4a5c1cdc6d8d2907099bdd5a776ed8

Note that the permissions were added to the `TaskRole` in the service yaml file, not the `ECSRole` in the ecs-cluster yaml file.

**Comment by MikeTheCanuck** [comment]
No, I haven't seen any stack deploy/update failures this week, and I've been hammering the stack, though not by making any changes to the 2017 Fargate services - so perhaps that was just a fever dream after all.  I'll close and re-open if this resurfaces.
