### ISSUE TITLE
Add www.civicplatform.org redirect

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic-devops#273]
Instructions: Replace text below with details corresponding to your issue

**TEAM NAME:** Platform
**PRIORITY (1-5):** P3
(I would really like this fixed prior to demo day. I think it's easy? I hope it's easy?)

**Description of issue**

www.civicplatform.org needs to redirect to civicplatform.org

**Error Message/Logs**

<img width="787" alt="image" src="https://user-images.githubusercontent.com/7065695/64492157-f191d500-d225-11e9-82b0-77cd03c0b866.png">

**Reproduction Steps**
www.civicplatform.org

**Screenshots/GIF**

> Provide any useful screenshots of errors or GIFs of issues that occur.

**Priority/Impact**

Anyone who adds a www in front of civicplatform.org currently would think that the site is broken.

I believe a non-trivial number of users are impacted by this bug.

**Comment by bhgrant8** [comment]
Adding @MikeTheCanuck and @DingoEatingFuzz here, as this would be configured in infrastructure level.

I see that the host2 referencing `www.civicplatform.org` is commented out here in our cloud formation `master.yaml`:

https://github.com/hackoregon/hackoregon-aws-infrastructure/blob/master/master.yaml#L177

Though I think there maybe dns configuration needed as well, or is it all in cloud formation currently?

https://github.com/hackoregon/civic-devops/issues/172

**Comment by MikeTheCanuck** [comment]
We’re pushing DNS changes through CF wherever possible. However, I failed to figure out a similar redirect a couple of weeks ago (though it was in the other direction IIRC).  I’d like to take a look at this tonight and see if I can wrangle it into our infra-as-code stack.

**Comment by MikeTheCanuck** [comment]
Huh, looks like someone already plugged it in manually

Edit: oh heck, that was me:
https://github.com/hackoregon/hackoregon-aws-infrastructure/pull/87/files#diff-675447e39c574d546b496dca60f801b7R104

**Comment by MikeTheCanuck** [comment]
With https://github.com/hackoregon/hackoregon-aws-infrastructure/pull/91 I have enabled ALB to properly route all requests for www.civicplatform.org to reach the container on which that code is hosted.
