### ISSUE TITLE
Deployment of 2018 container is failing

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic-devops#278]
**TEAM NAME:** Platform
**PRIORITY (1-5):** 1

**Description of issue**

The deployment of the 2018 container is failing, meaning that new commits to master in the[ civic repo](https://github.com/hackoregon/civic) are not being deployed to civicplatform.org

**Error Message/Logs**

EDIT -- removed irrelevant logs

**Reproduction Steps**

Merge a change to master in the [civic repo](https://github.com/hackoregon/civic). Deploy shows success, but hidden failure under make deploy.

**Priority/Impact**

Prevents any improvements to civicplatform.org

**Comment by jaronheard** [comment]
On further research, I see this issue in the logs from prior to Demo Day, where new versions have definitely been deployed.

**Comment by jaronheard** [comment]
It looks like this was the last deployed change:
https://github.com/hackoregon/civic/pull/1021#event-2634842658

Which looks like it was just prior to this being merged:
https://github.com/hackoregon/hackoregon-aws-infrastructure/pull/91

**Comment by MikeTheCanuck** [comment]
OK, this looks like we missed updating Travis env vars to use the new ECS Service Name for the migrated ECS service for CivicPlatformService. If that’s true then I’ll take the opportunity to rename the Resources entries as well. I’ll be back in a computer tonight.

**Comment by MikeTheCanuck** [comment]
Redeployed the cluster (a few times) to update service names for the two frontend services (and a couple of retries to get the usual ListenerPriority & TargetGroup cleaned up correctly), sync'd with this commit:
https://github.com/hackoregon/hackoregon-aws-infrastructure/commit/0112199840a3b707558fcb6f92286b3b0440359e

Grabbed the new service names from ECS and updated the Civic project's ECS_SERVICE_2017 and ECS_SERVICE_2018 env vars to match.

**Comment by jaronheard** [comment]
This is now working properly again! Thanks @MikeTheCanuck !
