### ISSUE TITLE
Host and serve DOGAMI raster tiles

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hackoregon/civic-devops#35]
Disaster Resilience has a sizable (3GB) set of vector tiles that they would like to be able to share among team members for reference in research and analysis. Potentially for production as well.

The best way to do this is to host the tiles in S3 and make a quick webpage with Leaflet or Mapbox using that S3 bucket as a tile source.

**Steps**
- [ ] Get DOGAMI tiles
- [ ] Convert DOGAMI tiles to a compact flat file system compatible with Mapbox and Leaflet
- [ ] Upload tiles to publicly readable S3 Bucket
- [ ] Make a public Leaflet or Mapbox map using the new tiles (probably in Glitch)

**Comment by MikeTheCanuck** [comment]
Questions:
1. who to contact to get DOGAMI tiles?
2. what is meant by "compact flat file system", and what are Mapbox and Leaflet?  What does the end result have to look like (what is the acceptance criterion)?
3. same bucket as distributable data, or is this more like production assets that are used by an API or React app?
4. what does it mean to make a public Leaflet or Mapbox map?  What does the end result have to look like?  What is Glitch?

Who can work on this with one of the DevOps squadroneers?

**Comment by DingoEatingFuzz** [comment]
> who to contact to get DOGAMI tiles?

The point-person from the disaster team is @LepoutreA, who already has the tile converted to a Tiff format.

> what is meant by "compact flat file system", and what are Mapbox and Leaflet? What does the end result have to look like (what is the acceptance criterion)?

This is how tile files are stored on disk to be served by mapping software (see [Tilesets](https://www.mapbox.com/help/define-tileset/)). Mapbox (specifically mapbox-gl) and Leaflet are web-based mapping software that would serve tiles in a similar fashion to Google Maps.

> same bucket as distributable data, or is this more like production assets that are used by an API or React app?

It's not exactly the same as archived data, but I wouldn't call it production assets yet either. It's unknown right now whether or not these will be a part of the final product. 

Functionally, it isn't too important where they live, since any URL will work as long as the x/y/z expected folder structure is adhered to (see [tiles URL in housing from last year](https://github.com/hackoregon/civic/blob/master/packages/housing/src/components/Map/index.js#L15)).

> what does it mean to make a public Leaflet or Mapbox map? What does the end result have to look like? What is Glitch?

Any ol' publicly hosted web page with the Leaftlet or Mapbox map on it. Glitch is free online editor/page hosting tool. Example: https://glitch.com/edit/#!/seed-building?path=map2.js:14:14

> Who can work on this with one of the DevOps squadroneers?

I figured I'd hammer it out with @LepoutreA once I get @rcallihan set up with AWS creds.

**Comment by LepoutreA** [comment]
Hi Michael

The converted rasters are located on the Google drive
https://drive.google.com/file/d/1aKTLRfHcWPYaSTRG8rR49h9MbaLacPPC/view?usp=drivesdk
Let me know if you have any questions,

Adrien

**Comment by DingoEatingFuzz** [comment]
This is done.

Hosted map: https://hacko-dogami-raster.glitch.me/
Remixable map source: https://glitch.com/edit/#!/hacko-dogami-raster?path=index.html:1:0
Disaster Resilience PR: https://github.com/hackoregon/disaster-resilience/pull/67
