### ISSUE TITLE
Branch create-db-instances updates unrelated files

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#37]
In the branch [create-db-instances](https://github.com/hackoregon/civic-devops/tree/create-db-instances) there are two files that unnecessarily update data that's been updated elsewhere.

I believe this occurred because the `git checkout -b create-db-instances` command was run from within an existing feature branch, rather than created cleanly from `master`.

The two files that I'd like to see taken back to their current state in `master` (so they don't show up in the forthcoming Pull Request) are:
- README.md
- create-database-development.sh

**Comment by MikeTheCanuck** [comment]
This blocks #25.

**Comment by khashf** [comment]
> The two files that I'd like to see taken back to their current state in master (so they don't show up in the forthcoming Pull Request) are:
> 
> README.md
> create-database-development.sh

Fixed: 0ade4634387d419b6436f64defface265ec0eaa9
