### ISSUE TITLE
Create instructions to extend an existing EBS volume for PGDATA

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#38]
One of the major blockers to deploying the developer database is that we have no idea how much disk volume the initial databases will consume - will it be 10GB or 200GB?  The cost differential is substantial, but if we target too small then additional databases won't be deployable.

We need a procedure (as automatable as possible) to grow the EBS volume (used for storing PGDATA) at any time, without having to take the database offline for extended periods - or having to build a new database server with a larger volume, then migrate the data.

The solution should allow an EC2 privileged operator to:
- specify an EBS volume instance
- select the new volume size at runtime
- extend the associated filesystem to fill the new volume

The solution should:
- specify an example command line based on the `aws` command line [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/cli-modify.html) to grow the volume
- specify the command to shut down the database server (nicely, if there are no active connections, and disable all new incoming connections)
- specify the command to discover the device name of the volume
- specify the command to resize the filesystem
- specify the command to restart the database server

This solution does not need to consider:
- automatically discovering the appropriate volume ID from an instance ID or 'Name' Tag for the instance or volume
- changing type of underlying disk (e.g. from `gp2` to `io1`
- shrinking the volume (not possible)
- working with partitioned disk volumes (each volume will only contain a single partition)

**Comment by iant01** [comment]
Pushed and created Pull request for the Extend EBS and S3 LifeCycle docs.
#53

**Comment by MikeTheCanuck** [comment]
Resolved by #53
