### ISSUE TITLE
Branch 'restore-db' contains two unrelated sets of changes that need to be two pull requests

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#40]
In the branch `restore-db` there are two sets of changes that belong in separate PRs:
1. the `restore-database.sh` script that takes a local backup file and restores it to the database
2. the changes to `create-ec2-machine-database.sh` and related files, which create some additional flexibility in creating additional, different database VM's in the future.

Please clean out all files but (1) from this `restore-db` branch and it can be submitted as one PR.

Please re-submit the other files and changes as a separate branch and that can be submitted as another PR.

**Comment by khashf** [comment]
Fixed by 88e73b133ef5830c3bc18b80ef4ddfc02b22a8ab
