### ISSUE TITLE
Role needed to assign to our PostgreSQL EC2 machine for S3 access

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#41]
During the restore of database backups from S3, the EC2 VM will need the ability to authenticate to the hacko-data-archive bucket.  This can either be accomplished by uploading AWS keys to the VM (undesirable) or assigning a Role with appropriate permissions to the machine (more desirable).

Ian and I explored the console and we believe that this could be accomplished with a single Role that includes a single Policy: "AmazonS3ReadOnlyAccess".  If you're looking for naming suggestions, I suggest "EC2-Read-S3-Buckets" - in fact, it appears that the IAM console allowed me to create this Role but wouldn't let me attach a Policy:
https://console.aws.amazon.com/iam/home?region=us-west-2#/roles/EC2-Read-S3-Buckets

**Comment by DingoEatingFuzz** [comment]
I can create this role, but the `hacko-data-archive` bucket is public to the world so it shouldn't be necessary.

I'm also still hazy on why the PostgreSQL EC2 VM would need read access to that particular bucket.

**Comment by znmeb** [comment]
The only thing the VM needs to be able to read is database dumps, not *everything* in the bucket, right? And it's the *shell* that needs to read those, not the database.

**Comment by MikeTheCanuck** [comment]
Here's where the creds/Role would be necessary:

```
$ aws s3 cp s3://hacko-data-archive/2018-transporation-systems/data/interim/passenger_census.backup .
fatal error: Unable to locate credentials
```

We could build on a `wget` or `curl` approach as well - I was hoping we could (a) take the most agnostic view of URIs (i.e. not bake in `us-west-2` anywhere we don't absolutely have to) and (b) not have to worry about whether https:// network transfers would cost money each time as well, but this isn't exactly the end of the world:

```
wget https://s3-us-west-2.amazonaws.com/hacko-data-archive/2018-transportation-systems/data/interim/passenger_census.backup
```

**Comment by DingoEatingFuzz** [comment]
I believe this is done. Reopen if there's still something left.

**Comment by MikeTheCanuck** [comment]
@DingoEatingFuzz please in the future, note in during close what change was made to determine how the problem was solved.  I didn't see any indication here that a new role had been created (or that some change had been made to an existing role) - thankfully I have enough IAM privileges to find it for myself.

Also, I believe it would be better to assign the issue back to the reporter for them to confirm that the solution works, before closing the issue.  I just tried to attach the `EC2-Postgres` IAM role to the `hacko-postgresql-development` VM instance and it reported the following error along with a failure:

```
Error
You are not authorized to perform this operation. Encoded authorization failure message: hu4lqqsBojJEhnS3ECGTK2H0gKCxA6uA3x2aX4YXa2qCDVYljXbRHMj39MXyg6-fzHFT3OGSD2mW5cph011pvGArqkOo6hugoqtPftJTIo1LtfBBnMrz2zWPFEc2gcTcdTD1AyYLvV5L6UcOgsz2kkopPiZmk0Cy5Y_b45u1zwZJ5tRwsr_X2VVg8zW1_8zo1Gq7E8SjxmWuCOStlkK5GqTRDdclidEv1GyMqEnn6vvn_Om3dwjyZYCbBsace106yhuddDbauCymF2qCrDtKga_bpb8CaF4NVoNGQv4krrRsaHPg9BQvV9FNS6D7C1TuJmWR3vufmYYJV0atmffa3EAg688RMTfaer97B0p1A-SEYUdGbNWVP_4M6ULg1WlA3Vv3Nr6uIC8DvCu1B_NYqsI07PQCF49o2Qi4_w8SM2abe5_rhVWxr5o_K5SMpLkagrbp2__o2Y0BeYkf3Rnsi5tXJfeMipMMbr7fsl9BYtfgCuXs8kOQ_I4G6r1dJTsTTwy81t0YOlVLIhJJiuyk1Gbj-J4i
```

**Comment by MikeTheCanuck** [comment]
This is still broken. Thus we are still paying the bandwidth costs for every backup download to the VM.
