### ISSUE TITLE
Remove hard-coded settings from the create-ec2-machine-database.sh script

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#43]
Make a few mods to the  [create-ec2-machine-database.sh](https://github.com/hackoregon/civic-devops/blob/master/bin/create-ec2-machine-database.sh) script to make it more flexible:
- [x] Make the VolumeSize a variable
- [x] Make the VolumeType selection a variable
- [x] Make the DeleteOnTermination selection a variable
- [x] Confirm that the " characters must be \escaped in the JSON block of `--block-device-mappings`, or remove that code if superfluous

**Comment by khashf** [comment]
> - [x] Confirm that the " characters must be \escaped in the JSON block of `--block-device-mappings`, or remove that code if superfluous
I confirmed that the `"` must be \escaped in the JSON block *if* that is either property name or a string. Also, it's an error if we surround number or boolean values by `\"`

Other objectives have been completed.

PR https://github.com/hackoregon/civic-devops/pull/63

**Comment by MikeTheCanuck** [comment]
PR #63 is merged
