### ISSUE TITLE
Investigate adding PostgreSQL server to the Cloud Formation scripts

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#61]
With #3, #17, #25 and #18, we have a working, repeatable (but manually-initiated) process for building the database server.

When these kinds of automation are able to be marshalled by Cloud Formation scripts, we should do so.

It's unclear whether this PostgreSQL machine build is the kind of operation that could or should be integrated into Cloud Formation.  (I have forgotten nearly everything I knew about the applicability of CF to problems like this.)

Could someone please check out whether and how this should be done?

Assume that the result should be integrated into the existing CF scripts here:
https://github.com/hackoregon/hackoregon-aws-infrastructure

**Comment by khashf** [comment]
PR made https://github.com/hackoregon/civic-devops/pull/69
