### ISSUE TITLE
problem: devops code changes have to be replicated between 5 API repos

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#65]
Last year, there were a few times when we discovered a better way of doing something "devops-y" e.g. an improvement to one of the scripts in the `/bin` directory like enabling command-line parameters.  Then we had to replicate those changes to each of the other four repos.  Which wasn't a big effort (because some of us had commit rights to every backend repo), but was still an inconvenience and an effort.

It would be awesome to have a way for our "build pipeline" types of files - mostly the stuff in `/bin` - to be abstracted so that if a change was made to one of the files, it would only have to be made in one place and all dependent projects would automatically inherit the benefit of that change.

**Comment by znmeb** [comment]
Can you wire this up with Travis CI somehow? You push a change to a repo and the other repos get a signal via a commit hook?
