### ISSUE TITLE
Assess the changes needed in CloudFormation templates when we bring a new Docker container online

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#66]
All the 2017 APIs are hosted in similarly-configured Docker containers, and each of them has a CloudFormation configuration to enable us to rebuild the infrastructure - deploy additional ECS hosts in new AZ's or new regions, or rebuild the existing infrastructure from scratch.

It's unclear what all we need to do when a new container needs to be integrated in the existing infrastructure - what new CF templates have to be generated, which existing templates have to be updated, and what consequential changes to the overall architecture (e.g. EC2 host sizing, memory allocation re-balancing, routing, IP address allocation?) need to be made.

We need a checklist of "here's what needs to be updated in CloudFormation and around it when landing a new container".

**Comment by bhgrant8** [comment]
Referencing the original source is a good place to start on this:
https://github.com/aws-samples/ecs-refarch-cloudformation

AMIs are one thing I believe needs some updating - think the above link has some recommendations if i remember correctly

**Comment by MikeTheCanuck** [comment]
So it turns out that the reference architecture (and our clone of it) outline the work needed to add a new service to the existing infrastructure:
https://github.com/hackoregon/hackoregon-aws-infrastructure#create-a-new-service

Could someone please validate this is all it takes to add something to an existing ECS deployment?

**Comment by khashf** [comment]
Does one need to spin up the whole infra to validate this HOWTO?

**Comment by iant01** [comment]
Status friday 5/11: was able to spin up all but the transportation-service container. Service failed to start because there was insufficient memory on either of the ecs instances for it to start. There is atleast one difference between the CF templates in hacko-infrastructure-cfn bucket and whatr is currently running in that the templates spin up t2-micro instances and the current running are t2-large instances. I will also check the cpu and memory reservation settings.

**Comment by khashf** [comment]
Status: Friday 5/11.
I was able to deploy one of the two services of the [Exemplar 2018 API](https://github.com/hackoregon/backend-examplar-2018) to ECS successfully. The succeed service is the `db_development`. The unsuccessful is `api` service.

More details at issue https://github.com/hackoregon/civic-devops/issues/87

**Comment by MikeTheCanuck** [comment]
@iant01 : If you have a pattern that lands a container image on an ECS instance, that's the missing step we need.  Debugging a container that lands but isn't successfully running is not necessary at this point - that's a problem we grapple with either way.  Unless there's a problem routing to the IP listening app in the container - is there some way to point it at a micro-container image that has a tiny web server that just says "yep, you've found me"?

@khashf: Let's focus on the good news: you have found a pattern that gets a container running in ECS.  How do you know that the db_development service is successfully deployed?  Is it that the **service** in the ECS cluster definition stays running?  Or were you able to connect to the database with a client software such as `psql` or `PGAdmin`?  If you have proven not only the container lives but the containerized app can be reached by IP, then let's get to the essential changes in the templates.  What line numbers of the `master.yaml` are the bits that absolutely need to be added/changed from the baseline master.yaml, so that we can add e.g. the db-service.yaml to the cluster?

**Comment by khashf** [comment]
Status Saturday 5/12
* Done: Resolved ECS service hanging issue.
* Current roadblock encountering: API service cannot connect to DB. 
* Plan: 
  * Waiting for https://github.com/hackoregon/civic-devops/issues/89
  * Switch to `./bin/build.sh -p` (build production image) instead of `development` and see

**Comment by MikeTheCanuck** [comment]
@khashf - re: "roadblock - API service cannot connect to DB"

Is there any chance that the DB container doesn't have an ENTRYPOINT defined, and thus the database just never gets started?  @nam20485 made a comment [here](https://github.com/hackoregon/backend-examplar-2018/issues/64#issuecomment-388182211) that made me wonder, and since I can't see your current code I'm only guessing.

**Comment by khashf** [comment]
You're probably right. 
Before I resume work on Monday night, here is what I get in CloudWatch log for the DB service:
```
2018-05-13 06:35:24
Loading older events...
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
Data page checksums are disabled.
fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
pg_ctl -D /var/lib/postgresql/data -l logfile start
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
WARNING: enabling "trust" authentication for local connections
Success. You can now start the database server using:
syncing data to disk ... ok
****************************************************
WARNING: No password has been set for the database.
This will allow anyone with access to the
Postgres port to access your database. In
Docker's default configuration, this is
effectively any other container on the same
system.
Use "-e POSTGRES_PASSWORD=password" to set
it in "docker run".
****************************************************
waiting for server to start....LOG: database system was shut down at 2018-05-13 06:35:25 UTC
LOG: MultiXact member wraparound protections are now enabled
LOG: database system is ready to accept connections
LOG: autovacuum launcher started
done
server started
ALTER ROLE
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/1make-dbsuper.sh
ALTER ROLE
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/restore-all.sh
Restoring /home/dbsuper/Backups/dead_songs.sql
SET
SET
SET
SET
SET
SET
SET
SET
DROP DATABASE
DROP ROLE
CREATE DATABASE
You are now connected to database "dead_songs" as user "postgres".
CREATE TABLE
INSERT 0 1
INSERT 0 1
INSERT 0 1
Restore completed
LOG: received fast shutdown request
LOG: aborting any active transactions
LOG: autovacuum launcher shutting down
LOG: shutting down
waiting for server to shut down....LOG: database system is shut down
done
server stopped
PostgreSQL init process complete; ready for start up.
LOG: database system was shut down at 2018-05-13 06:35:27 UTC
LOG: MultiXact member wraparound protections are now enabled
LOG: database system is ready to accept connections
LOG: autovacuum launcher started
LOG: received smart shutdown request
LOG: autovacuum launcher shutting down
LOG: shutting down
LOG: database system is shut down
```

**Comment by BrianHGrant** [comment]
I think the root of this issue is the same mentioned in https://github.com/hackoregon/civic-devops/issues/89

Env variables are being set as they appear in the `docker_compose` files instead of based on the names in the django app itself. Try dropping the "DEVELOPMENT_" and "PRODUCTION_" prefixes in the CF templates.

The reason I set the variables to do this was for the ability to test a production build along side a development build locally without having to reset the env variables each time. If this proves to be the issue and adds to a layer of confusion, then it may not be a useful abstraction and I would be ok with some refactoring.

**Comment by khashf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The DB service never got started](https://trello.com/c/Z26ngm8Y/5-the-db-service-never-got-started)

**Comment by MikeTheCanuck** [comment]
Leaving aside the internals of the containers, we now fully understand (and have thoroughly tested) the changes necessary in CloudFormation templates to bring new ECS services online.

An example of the changes can be found here, where we're adding two new containerized web sites:
https://github.com/hackoregon/hackoregon-aws-infrastructure/pull/9
