### ISSUE TITLE
Dumb question: does CloudFormation deploy a "service" per-container, or per-docker-compose file?

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#68]

**Comment by BrianHGrant** [comment]
Not dumb at all, think this is the most clear answer I have found on services, tasks, clusters, and containers:

https://stackoverflow.com/questions/42960678/aws-ecs-running-task-vs-service

**Comment by MikeTheCanuck** [comment]
That's awesome - so for my posterity:

- Task Definitions define Tasks, which define the behaviour of 1+ containers
- Services control one or more Task instances

I'm inclined to start out each ECS Service with a single container per Task and dual Tasks per Service, as we did last year.  That makes it far easier to reason and troubleshoot the behaviour we're expecting from each API container.
