### ISSUE TITLE
AWS global access request

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#7]
One of the significant DevOps goals for the 2018 season is to improve on last year’s approach to
- managing monthly billings to reduce excess consumption
- enhancing IAM - make access controls more consistent across and within projects, reduce the proliferation of privileged accounts, focus on groups/roles-based management (rather than so many one-off requests for accounts we don’t even know if they’re still active).

To understand and get control over all of the unexpected billing across all the AWS services, we’ll at least need visibility across the account (and at least one or two of us will need the ability to make changes to any or all services).

To provide central roles-based access we’ll need visibility into the entire spread of objects being managed, and at least one or two of us will need the ability to make privileged changes in IAM.

**Comment by MikeTheCanuck** [comment]
@meganmckissack can you help us with this?

**Comment by meganmckissack** [comment]
I think we should talk about what access is needed.  You currently have a lot of permissions but I just sent everyone else read-only access so they can see what's going on.

The billing is not currently unexpected, I have billing alerts in place now.  It's mostly too many hands in the kitchen with not a real plan.  Dan gave me billing estimates for all new services, you can configure them with an aws budget tool, doesn't require HO account access, it's just that as we add services, we'll need to figure out projected costs, what is worth paying for, and etc.

We do have what pretty good groups in place for assigning user privileges, we'll just need to know what users need to do and then assign them to groups that have those permissions.

I can work on cleaning up some past no longer active users.

I'll add more info in slack

**Comment by MikeTheCanuck** [comment]
The needs are being addressed in other ways for now.
