### ISSUE TITLE
Generate working automation script for PostGIS from Ed's Dockerfile

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#72]
To add PostGIS support to an EC2 instance of PostgreSQL built from this script...:
https://github.com/hackoregon/civic-devops/blob/master/bin/create-database-development.sh

...we'll need a shell script that builds and installs PostGIS and its dependencies on an Amazon Linux 2 VM that works after the above script is completed.  (Unknown whether the PostGIS stuff has to be run **after** PostgreSQL is installed but **before** it is configured - i.e. between lines 24 and 49 of the above script, but let's assume it can be done for now.  Otherwise we'll have to refactor the above script for optional inclusion of the PostGIS bits.)

Ed pointed me at the following Dockerfile - it'll need some significant refactoring to make this work as a shell script.  I'll get started and see how far I get:
https://github.com/hackoregon/data-science-pet-containers/blob/master/containers/Dockerfile.amazon-postgis

**Comment by MikeTheCanuck** [comment]
I'll be working in branch [add-PostGIS-automation](https://github.com/hackoregon/civic-devops/tree/add-PostGIS-automation)

**Comment by MikeTheCanuck** [comment]
Notable findings and questions along the way, round 1:

Is `cmake` really necessary here?  Does CGAL really have to be converted to a cross-platform set of sources?  From what my testing shows, this step downloads a 34 MB (!) "shell script", which is 99% an encoded `.tar.gz` file.  Seems a pretty heavyweight approach, though I see it explicitly called out here:
https://doc.cgal.org/latest/Manual/installation.html#secconfigwithcmake

**Comment by znmeb** [comment]
1. I had to build `cmake` because the version in Amazon Linux 2 was too old.
2. `gdal` is huge - it's one of those "swiss army knife" toolsets that does many things. What I don't know is how much of that is actually required in PostGIS or whether it's even possible to build a subset.

**Comment by MikeTheCanuck** [comment]
notable findings, round 2:

Line 32 results in "Permission denied" error, even when I prepend `sudo` to the command:
 `sudo echo "/usr/local/lib" > /etc/ld.so.conf.d/usr_local_lib.conf `

**Comment by znmeb** [comment]
I don't remember whether I've run into that or not - I usually `sudo cp` a file rather than using `echo`.

**Comment by iant01** [comment]
worked out the final dependency for pgrouting, cleaned up logging an set to exit on error. PR submitted, ED can work with postGIS to check it and tools out once built into database server instance by Mike. build took six hours on ec2 micro linux2 instance.

**Comment by MikeTheCanuck** [comment]
Resolved with #74

**Comment by znmeb** [comment]
@MikeTheCanuck I made a compressed SQL backup from the disaster resilience database you can use for testing. @mxmoss and @nam20485 both have copies and it's in Google Drive if you want a copy too. ;-)
