### ISSUE TITLE
Get the "Civic Admins" GitHub Team added to all backend repos for 2017-2018

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#73]
To be able to configure Travis for the API container pipelines, we'll need to have authorization in the GitHub repo for each API.  I'm not sure if it's Admin access or just Contributor (I could survey all such projects and see where my access is currently enabled or disabled).

Without this, CI/CD will be time-consuming to setup and impossible to maintain as we add/enhance the Settings.

## GitHub Repositories
-  [x] [disaster-resilience-backend](https://github.com/hackoregon/disaster-resilience-backend)
-  [x] [housing-2018](https://github.com/hackoregon/housing-2018)
-  [x] [elections-2018-backend](https://github.com/hackoregon/elections-2018-backend)
-  [x] [neighborhood-development](https://github.com/hackoregon/neighborhoods-2018)
-  [x] [transportation-system-backend](https://github.com/hackoregon/transportation-system-backend)
 - [x] [some new transportation API]

**Comment by MikeTheCanuck** [comment]
OK, according to #126 there's a new API repo coming online - once that's covered we're covered.

**Comment by bhgrant8** [comment]
so as per #126 devops has been added to braised_kale:

https://github.com/hackoregon/braised_kale
