### ISSUE TITLE
Create ECS services for Civic-2017 and Civic-2018

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hackoregon/civic-devops#76]
These will be the two ECS services for the web frontend. Both are very similar to the django services in that they are a containerized web service with the need to expose a single port.

The port for these two services is 3000. 

The resources requirements is unknown, but it ought to be extremely low considered how thing the server-side component of the websites are.

These services should be accessible at:

  - **civic-2017**: 2017.civicpdx.org
  - **civic-2018**: staging-2018.civicpdx.org

Once we are closer to demo day, we'll want to switch civic-2018 over to 2018.civicpdx.org.

**Comment by DingoEatingFuzz** [comment]
Related Civic issue: https://github.com/hackoregon/civic/pull/80

**Comment by iant01** [comment]
This has been accomplished in a separate account successfully, trying out how to use the modifications to master.yaml and the two new service.yaml files with the current CF stack to make sure only the new services are added and the entire current running stack is not removec and replaced. Need to compare the templates used for the last spin up (may last year) against those in S3 and github) as there are currently differences that exist in the running stack.

**Comment by MikeTheCanuck** [comment]
I would really appreciate some how-to details along the way, rather than continuing to wait for someone to show us how to achieve these results that are mentioned but still not repeatable by anyone else.

**Comment by MikeTheCanuck** [comment]
I've written up the how-to guide that I was hoping to see, and we've completed the stack update to enable the Civic2017Service to be deployed.  (Civic2018Service will deploy when [this bug](https://github.com/hackoregon/civic/pull/120#pullrequestreview-121297465) gets addressed.

**Comment by MikeTheCanuck** [comment]
Given that the two containers are now listening on the following URLs, I consider this ticket closed:
http://staging-2018.civicpdx.org
http://2017.civicpdx.org
