### ISSUE TITLE
Create deployer keys and ECR repositories and sufficient permissions to allow image uploads for each API project

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#78]
In experimenting with the "deploy" phase of the **transportation-systems-backend** project, I discovered that when I re-used "Deployer Keys" (an AWS key pair) from last year's transportation API project, that the `docker push` command would very precisely fail after it had obtained the 12-hour token via `aws ecr get-login`:

```
denied: User: arn:aws:iam::845828040396:user/s3-staging-deploy-transportation is not authorized to perform: ecr:InitiateLayerUpload on resource: arn:aws:ecr:us-west-2:845828040396:repository/production/transportation-systems-service
```

I have looked closely at the ECR repository from last year and discovered that the permissions were setup very restrictively, such that in the Policy document for each specific repository, only one specific **arn** is authorized to perform only very specific actions.

- [x] Deployer keys (one set for all projects, or one per project) need to be generated
- [x] ECR repositories need to be created e.g. **production/transportation-systems-service**
- [x] Policy documents need to be generated and assigned to each ECR repo

**Comment by nam20485** [comment]
I have deploy working from travis to my own AWS ECR (test I created under my own account). The only thing missing from my testing is having a real HackOregon ECR to push to. When you get something up, let me know if you want me to test against it.

**Comment by MikeTheCanuck** [comment]
Thanks Nathan - I’d love to coordinate with you when I get the deployed keys, repo and Policy arranged. Are you with the Disaster Reslience team? I could try getting those set up there first or after transportation - probably will just depend on who I notice on Slack when I’m ready to make this go.

**Comment by nam20485** [comment]
Sounds good. Yes I am a member of the Disaster Resilience team.

**Comment by MikeTheCanuck** [comment]
OKL

- keys for a single user "2018-ecs-ecr-deployer" have been generated
- repositories for all five 2018 API projects have been created
- permissions for that user to perform "push" and "pull" operations have been applied to those repositories
