### ISSUE TITLE
Apply lifecycle policies to ECR repositories to mitigate continual storage consumption

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#80]
Hack Oregon has a growing number of ECR repositories here:
https://us-west-2.console.aws.amazon.com/ecs/home?region=us-west-2#/repositories

One per GitHub repo that generates Docker containers (rather than one per project season or one repo for the entire organization) gives us the ability to set lifecycle policy that keeps e.g. newest five images, in case we have some need to roll back an ECS deployment directly from the ECR images (rather than by kicking off a new Travis build/test/deploy cycle from source code).

However, we have no lifecycle policy in place at this time to restrict the number of images stored in any of the repos.  When last we looked, the 2017 repos each contained > 100 images, each image sized at hundreds of MB.  Even at S3 pricing levels, this kind of storage volume adds up to real money.

Task: apply a lifecycle policy to each of the repositories in the above collection, so that we only keep the last five images (including the image tagged `latest`).

**Comment by iant01** [comment]
The ECR container repos have the following lifecycle policy applied which removes all but the 10 latest untagged container images. Tagged container images such as "latest" and any other tagged images are not affected.

{
"rules": [
{
"rulePriority": 10,
"description": "delete all but latest 10 untagged",
"selection": {
"tagStatus": "untagged",
"countType": "imageCountMoreThan",
"countNumber": 10
},
"action": {
"type": "expire"
}
}
]
}
