### ISSUE TITLE
Delete old container images from "integration/*" ECR repos

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#83]
Last year's ECR repos (all prefixed with "integration/") are stuffed full of excess container images.  We only need the last five or so, and we've already done this for **integration/budget-service** but there's terabytes more of these to go.

**Comment by MikeTheCanuck** [comment]
Great, thank you. When you make a change like this that doesn’t have code in a repo, would you please document the specific change in your update so we can have an historical record of how to make such changes in the future? Thanks!

**Comment by iant01** [comment]
The ECR container repos have the following lifecycle policy applied which removes all but the 10 latest untagged container images. Tagged container images such as "latest" and any other tagged images are not affected.

{
  "rules": [
    {
      "rulePriority": 10,
      "description": "delete all but latest 10 untagged",
      "selection": {
        "tagStatus": "untagged",
        "countType": "imageCountMoreThan",
        "countNumber": 10
      },
      "action": {
        "type": "expire"
      }
    }
  ]
}

**Comment by iant01** [comment]
the lifecycle policy automatically removed all but the latest 10 untagged images (tagged ones are left)
