### ISSUE TITLE
ECS was unable to run container of the `api` image built by the ExemplarAPI 2018

### ISSUE THREAD

**Issue by khashf** [hackoregon/civic-devops#87]
# Details 

What I did and saw, in order of time:

1. I used to `master` branch and followed [the instruction in the master branch](https://github.com/hackoregon/backend-examplar-2018/tree/master#run-the-sample) of that repo and was able to successfully run the API locally.

2. Then, as to I see, by `./bin/build.sh -l` command, this project builds 2 images: `api` and `db_development`. Thus, I pushed these 2 images to my AWS ECR so I can add 2 corresponding ECS services from these 2 images.

3. Modified and deploy CloudFormation Stack. For what exactly I modified to add services to last year CF stack, see the [whole diff of my fork here](https://github.com/khashf/hackoregon-aws-infrastructure/pull/1/files)

4. Everything was created successfully, including the new `db_development` service, except the `api` service. From the event log, I saw that ECS::Service didn't log out as "Creation Failed" but "Creation in Progress", more detail is "Resource Creation Initiated" as you can see in the below screenshots.

The following screenshots show what I have looked at and saw in the Console.

(1)

![image](https://user-images.githubusercontent.com/6059347/39953555-5536c0ca-5563-11e8-981f-66281c0a8f05.png)

(2)

![image](https://user-images.githubusercontent.com/6059347/39953643-409a17a0-5565-11e8-9f57-76f7991212c5.png)

(3)

![image](https://user-images.githubusercontent.com/6059347/39953884-c3402c36-5569-11e8-8be5-1882d032eedb.png)

(4)

![image](https://user-images.githubusercontent.com/6059347/39953596-3d1dcc4e-5564-11e8-9c8b-8bad2af66a1f.png)

(5)

![image](https://user-images.githubusercontent.com/6059347/39953672-b253fe9c-5565-11e8-92a2-d2b6f2502e81.png)

(6)

![image](https://user-images.githubusercontent.com/6059347/39953610-869c35fe-5564-11e8-8207-50ed32fba86f.png)

(7) 

![image](https://user-images.githubusercontent.com/6059347/39953615-9b66e43e-5564-11e8-8a3b-7e4110cba6a1.png)

(8)

![image](https://user-images.githubusercontent.com/6059347/39953718-4fe70e4c-5566-11e8-81e3-646e2f5812ab.png)

# Thoughts and Comments

* I suspect the reason for this is what @MikeTheCanuck has guessed in the latest meeting: ECS was unable to run the container as it repeatedly ran and de-registered the task in the second image above.

* AWS has some tips on how to troubleshoot ECS Task Error [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/stopped-task-errors.html)

* There is no log left in the failed `Task` as you can see from the above images

* The possibility that I don't have permission to access images in `hacko` ECR is crossed because I have tried both (1) with <last year service> + <new serives (exemplar service)> and (2) without last year images. Both trials result in the same symptom above.

**Comment by khashf** [comment]
### Updates #1 **5/11 21:50**
I'm following the lead from image #7 above. The fail details is shown "Exitcode0". This seems relates to that last item in a troubleshooting tip [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/stopped-task-errors.html) - "Essential container in task exited". @znmeb @BrianHGrant Do you have any thought on what might happen here?

**Comment by khashf** [comment]
### Update #2 **5/11 22:05**
Someone had relevant event logs [here](https://forums.aws.amazon.com/message.jspa?messageID=709829).

**Comment by khashf** [comment]
### Update #3 **5/11 22:19**
Tried to access the ECS host of the failed tasks but was unable to

Img1

![image](https://user-images.githubusercontent.com/6059347/39953917-20f64338-556a-11e8-8602-99f0fb300a7a.png)

Img2

![image](https://user-images.githubusercontent.com/6059347/39953896-f080b27e-5569-11e8-9e8e-3f0d7493ccfe.png)

=======


=> Those 2 EC2 instances don't have public IP addresss. How can I `ssh` to them to see the more detailed ECS log at `/var/log/ecs`

=> I see that in our `hacko` AWS account, the ECS hosts also don't have Public IP addresses, too

**Comment by MikeTheCanuck** [comment]
The only thing I can think that would allow you to `ssh` into the EC2 instance is to use a "jump box" or "bastion host" that's already in that network, has a public IP address, and can route IP traffic to the EC2 instance.  Dan had a bastion host last year that he never explained, and I never figured out what it did, but that's probably what it was for.

**Comment by BrianHGrant** [comment]
So a few things I see here.

1. In step 2 you mention, './bin/build.sh -l', is this coming from an older version of the example? Current version shoud be using a -d flag, so would first say confirm are up to date. You may need to use staging not master (though maybe we just need to merge staging to master)

2. It looks like you added Parameters then commented them out on the cloudformation template are they being hardcoded somewhere?

3. The task not starting means that django start command is failing. The master branch might not have an entry point command in the Dockerfile and only in the compose, which @MiketheCanuk had determined was not correct for AWS as ECS does not recognize the compose files.

Typing this on my phone so I apologize for lack of hyperlinks.

**Comment by MikeTheCanuck** [comment]
Great catches Brian! 

Yes let’s merge to master - I’ll set up the PR if no one else gets a chance before me. 

I should do a sweep and see if every project repo has an ENTRYPOINT

**Comment by khashf** [comment]
@MikeTheCanuck 

- **Bastion Host**: I just tried to `ssh` to it and it was timeout. I cannot ping that Public IP address either - No ping response received.

**Comment by MikeTheCanuck** [comment]
Hi @khashf - I wouldn't be surprised if `ping` requests are blocked by default here, so that isn't necessarily a useful indication of trouble.  

Is it possible that the security group assigned to the Bastion Host only allows certain IP addresses incoming?  The screenshot you included implies otherwise, but "timed out" on tcp/22 when you're coming at it with a tcp/22 protocol seems...weird to say the least.

Have a look at the security group assigned to our current Bastion Host box in HackO's EC2 and compare to what is assigned to the Bastion Host box in your EC2 - pay particular attention to the Inbound tab, which is what I've messed up in the past when I've created a "timed out" condition for systems I'm locking down:
https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#SecurityGroups:groupId=sg-b22f3aca;sort=groupName

**Comment by khashf** [comment]
### Update **May 13 01:25**
The hanging issue has been fixed by adding `ENTRYPOINT` to `DOCKERFILE.api.development`. Detail is at issue #64 

However, the Bastion Host connection issue has not been resolved. So I'm closing this issue and create a new one at issue #90
