### ISSUE TITLE
Figure out where exactly we set env vars for Docker containers that follow backend-exemplar-2018

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#89]
Last year, we would download a `.py` file into the container while we were building the image.  That python script would set the env vars every time the container was started.

If I remember my conversation with Bryan correctly, the env var values (for API containers built on `backend-exemplar-2018` repo) would get passed in by ECS, not by any code inside the container.

I just spent some time with @khashf trying to figure out where we would set those values.  He pointed to the **Parameters** block in each Service's section of `master.yaml` as one place where the public env var values can be stored.  That's great, but what about $POSTGRES_PASSWORD?  We need to store our YAML templates in source control, and I'm not checking in our deepest secrets into a YAML file in GitHub (at least, I **hope** I never do).  We could store these YAML files just in S3, but that'll create the same problem we had this year trying to figure out where the "truth" is from last year's infrastructure, and S3 is not a good change-tracking system.

I thought there might be some way to manually create env vars in ECS console (similar to how we create env vars in Travis "Settings" console), but I couldn't find something like that when I looked today. (Maybe this is why we have the `project_config.py` pattern from last year?)

**Comment by MikeTheCanuck** [comment]
Paging @BrianHGrant @bhgrant8 if you've got any clues for us...

**Comment by BrianHGrant** [comment]
So instead of hardcoding the secure parameters into the YAML, you can configure to set within the UI and use the "no echo" flag so they are not displayed in logging. See my last 2 comments from this thread for AWS white paper reference and a rough sketch, that I did some basic testing to confirm would pass through to the service.

https://github.com/hackoregon/backend-examplar-2018/issues/13

**Comment by MikeTheCanuck** [comment]
@khashf I would definitely try spinning up your DB as an EC2 instance (you could even try setting it up with the templatized scripts that you and I worked on) and letting the API connect to that.  Sounds like a good plan.

**Comment by MikeTheCanuck** [comment]
@BrianHGrant Yeah you did mention that - I think I still don't understand how that approach is actually implemented on a service-by-service basis because there's so little documentation that describes "here's exactly how you format the Parameter in your YAML file" that's different from setting up a hard-coded parameter (or one that inherits at the service layer from one hard-coded in the master layer), and I just did a sweep and couldn't find *anything* that described where in the UI the admin actually inputs the non-echo'd parameter value.  

Like, does the parameter's value become a blank text box in the UI once ECS has ingested a template that includes an "input parameter" - but otherwise hides all traces of this configurable parameter UI when no such parameter has been defined?

**Comment by nam20485** [comment]
As far as the environment variables that are needed to get the development docker images up, see the backend-examplar-2018 repo's [sample.env](https://github.com/hackoregon/backend-examplar-2018/blob/staging/env.sample):

```
PROJECT_NAME=dead_songs
DEBUG=True

# the database superuser name - this is the default
DEVELOPMENT_POSTGRES_USER=postgres

# the database name the API will connect to - "dbname" in most PostgreSQL command-line tools
DEVELOPMENT_POSTGRES_NAME=dead_songs

# the database owner - automatic restore needs this
DEVELOPMENT_DATABASE_OWNER=sampleuser

# *service* name (*not* image name) of the database in the Docker network
DEVELOPMENT_POSTGRES_HOST=db_development

# port the database is listening on in the Docker network
DEVELOPMENT_POSTGRES_PORT=5432

# password for the PostgreSQL database superuser in the database container
DEVELOPMENT_POSTGRES_PASSWORD=sit-down-c0mic

# the password for the teams
DEVELOPMENT_TEAM_PASSWORD=d0wn!0ff!a!duck

# Django secret key in the API container
DEVELOPMENT_DJANGO_SECRET_KEY=r0ck.ar0und.the.c10ck
```

@khashf Two things that I see right off the bat: 

1. You are using a different $PROJECT_NAME than we usually do ("Dead-songs" vs. "dead_songs")
2. You are not setting $DEVELOPMENT_POSTGRES_OWNER in your environment. (Since you are having trouble connecting the DB maybe this could be responsible?)

If you are having trouble running the development images I would first ensure the images you built with `bin/build.sh -d` run successfully on your local system where you built them. This can be done by running the `bin/start.sh -d` command and then ensuring that the console shows the Django server successfully starting and that you can browse to the http endpoint. If this runs correctly then the images are built correctly and this would point to the ECS environment being the problem, not the images.

**Comment by iant01** [comment]
https://aws.amazon.com/blogs/compute/managing-secrets-for-amazon-ecs-applications-using-parameter-store-and-iam-roles-for-tasks/

This is a possibility, you would not define the policies in the CF templates just create them in the hacko account and reference the policies in the task definitions, so long as the aws cli is added to the container and the container programmed to make the needed aws cli calls to get the secret, it would be secure, would not expose any secrets in github code or CF templates in either github or S3.

**Comment by BrianHGrant** [comment]
Following up on @nam20485's comment, yes the env values being used are not current. Also in @khashf, I am continuing to see a reference to api_staging, so this would not be up to date, I am pretty sure we pulled the staging branch of the examplar (hehe) into master, so should no longer be using "staging" as an environment in anyway.

Next the log entries mentioned are from the psql wait script installed in the dev environment, which has been removed from current prod if my memory serves me well. The idea being that the api itself will not be started up until the db is up and running. If you are deploying the db and the api at the same time, as the dev environment does, this does prove useful to prevent the api from attempting to start before the db is up and running which causes an error. 

3rd. the DEVELOPMENT_POSTGRES_PASSWORD and all "DEVELOPMENT_" or "PRODUCTION_" variables that are used are only for the DOCKER_COMPOSE files. As we have determined that ECS does not use compose only the DOCKERFILES themselves, we would want to use what these vars are named in the DJANGO APP itself, which drops the prefixes for "POSTGRES_PASSWORD" and the like.

For example this line:
https://github.com/hackoregon/transportation-system-backend/blob/6c73ac36d8d7571a8566999f881c2dfc313a6b57/development-docker-compose.yml#L29

Shows how the various variables are string interpolated in the compose.

I was going to walk through an attempt to add the params into the Cloud Formation UI as previously mentioned with our current infrastructure but doing a quick read on the blog post @iant01 provided, think this may be a better option.

**Comment by khashf** [comment]
WIP: Currently working on this and issue #66

**Comment by khashf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The DB service never got started](https://trello.com/c/Z26ngm8Y/5-the-db-service-never-got-started)

**Comment by MikeTheCanuck** [comment]
I dove into some research tonight to figure out how to inject secrets at runtime into ECS containers, and spotted the Parameter Store reference.  Came here to mention it, and saw Ian's comment buried in the dogpile on Khuong's challenges with getting the containers running.  I'll spin off a separate issue #113 to document exactly how to use this.
