### ISSUE TITLE
Investigate the consequences of updating component-library on the Packages that depend on it

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#9]
We have confirmed that in the [Civic repo](https://github.com/hackoregon/civic), the 5 project Packages are able to build and start successfully:
- budget
- emergency-response
- homelesness
- housing
- transportation

One of the benefits of the monorepo is to be able to have common dependencies like the `component-library` be updated once, automatically imported into depending packages and for those depending packages to generally just work.

This scenario has not been tested since the monorepo project packages were stabilized, or else that success hasn't been documented.  If this process fails, then the monorepo will cascade fail as soon as someone decides to update a peer package like `component-library`.

Test this trivially just to ensure the monorepo actually gives us the benefit of this capability:
- make a trivial change (e.g. text string, comment, add a dummy function or an always-true statement) to the component-library code
- re-run the documented steps (`bootstrap`, `build`, `start`) for any of the 2017 Project packages

**Comment by DingoEatingFuzz** [comment]
Out of scope of the devops team and this devops repo.
