### ISSUE TITLE
Does spinning up a duplicate ECS cluster cause collisions between unique resources?

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#91]
We're having a helluva time debugging the current ECS infrastructure definition:
1.  code in GitHub repo (probably out of date with live production cluster) = https://github.com/hackoregon/hackoregon-aws-infrastructure
2. code in AWS S3 bucket (also probably out of date with live production cluster, and also probably out of sync with Github repo) = **hacko-infrastructure-cfn**

Spinning up this infrastructure in personal AWS accounts means that only one person has access to the console and all the troubleshooting logs, and the rest of us are losing precious days waiting to fix all the issues and start adding new containers/services to our ECS production cluster.

So the obvious, not-terribly-costly-if-we're-careful-about-shutting-it-down-quickly and potentially-accelerating-our-troubleshooting-efforts ideas is: why not spin up a duplicate cluster in the HackO account based on the CF templates we have (picking the `master.yaml` either from GitHub or just using the one that's already in the S3 bucket - whichever we think is more likely to be closest to production)?

The only reason I hesitate in the least about this is because there's a possibility (dunno if this is real or just in my head) that some of the core, unique resources might be hard-coded to the point that we could end up creating conflicts between the two clusters and actually degrade (temporarily, until we turn all the "testing duplicates" off, or maybe even permanently) the performance or operability of the existing production cluster.

It stands to reason that any such collisions/conflicts will be a result of whatever is defined in `master.yaml`, and maybe in the non-`service.yaml` templates that it depends on, and if there's nothing there that looks like a problem then we should feel confident that this is an experiment worth doing to expedite our troubleshooting of last year's brittle/under-documented CF infrastructure.

Here's a checklist of the things I or others should look into, all in the **Resources** section of the `master.yaml` (where `*` scares me most):
- [x] VPC *
- [x] SecurityGroups
- [x] ALB
- [x] ECS
- [x] BastionHost

And here are the Resources from the dependent templates that have my attention:
- VPC
- [x] InternetGateway *
- [x] InternetGatewayAttachment
- [x] PublicSubnet1 *
- [x] PublicSubnet2 *
- [x] PrivateSubnet1
- [x] PrivateSubnet2
- [x] NatGateway1EIP
- [x] NatGateway2EIP
- [x] NatGateway1 *
- [x] NatGateway2 *
- [x] PublicRouteTable *
- [x] DefaultPublicRoute *
- [x] PublicSubnet1RouteTableAssociation
- [x] PublicSubnet2RouteTableAssociation
- SecurityGroups *
- [x] BastionHostSecurityGroup
- [x] ECSHostSecurityGroup
- [x] DBSecurityGroup
- ALB
- [x] LoadBalancer
- [x] LoadBalancerListener
- [x] DefaultTargetGroup
- ECS
- [x] ECSCluster
- [x] ECSAutoScalingGroup
- [x] ECSLaunchConfiguration
- BastionHost
- [x] EC2Instance

## MANDATORY PROCEDURE
If we go to this trouble, anyone involved will document *exactly* every step that is take - both in the **Create Cluster** wizard (which seems to override/duplicate much of what's defined in the `master.yaml`, but not entirely), and in every step taken in any code or UI to "fix" problems we encounter in getting a duplicate cluster completely working.  There is no shortcut on this - we can't afford to not completely document how this damned thing is working (or what needs to be cleaned up next time we try to decipher the orchestration, which is always a cliff-climb of a learning curve).

## CLEANUP
We will need a joint effort after this is over to track down and kill off any and all of the AWS resources that are allocated by this effort (e.g. EIPs, ALB, VPCs, storage volumes, whatever lingers after we delete the cluster - no idea what all that might be, but there's likely something that doesn't clean up nicely).

**Comment by MikeTheCanuck** [comment]
Commentary:

## VPC
- InternetGateway has no resources - it's nearly a toggle
- NatGateway1EIP and NatGateway2EIP have no explicit values - which implies they're automagically assigned when the cluster/stack gets generated
- NatGateway1 and NatGateway1 appear to be assigned whatever value comes back for the EIPs, so that's automatic as well
- all the `*`Route`*` stuff seems pretty hands-free as well

## SecurityGroups
- all security group names are well-prefixed with the "EnvironmentName" so that should never collide
- the ingress/egress rules otherwise seem well-formed and nothing scares me in their details

## ALB
- nothing seems collision-worthy here either

## ECS
- even the ECSLaunchConfiguration hard-coded scripts are all well-parameterized
- as is the ECSRole configuration

**Comment by iant01** [comment]
The current S3 CF templates can be used to spin up an entire hacko environment in a separate VPC which keeps them entirely separated, but this will double the Hacko costs for the time the duplicate exists.
CF stack deletion removes everything the stack created (provided  the stack items are not manually messed with such that CF gets confused.

**Comment by iant01** [comment]
The current master.yaml file and associated service.yaml files create an entire stack in a new VPC if master.yaml is used to create a NEW stack (as opposed to a change-set or update-stack) there will be no collision between the current existing stack and the new stack. to access the new stack via the new load balancer, either the existing aliases would need modified to be redirected to the new load balancer or additional aliases would need to be created to point to the new load balancer.

What you can not do is attempt to cherry pick some parts of the resources (ie. you could not create just a new ECS cluster and have it use the existing load balancer as the listener rules would collide.

**Comment by MikeTheCanuck** [comment]
Fair enough.

Now that we have finished doing testing with clusters in non-HackO accounts, and we've figured out the delta that needs to be added for each new service, we no longer have a need to spin up a test cluster in the HackO account to be able to resolve our testing questions.
