### ISSUE TITLE
"Outdated ECS Agent" warning in hacko-integration ECS Instances

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#92]
Browse to the ECS cluster **hacko-integration**, and click on the **ECS Instances** tab.  It presents a massive warning:

> Outdated ECS Agent
> One or more container instances are not running the latest version of the Amazon ECS container agent.

Each of the two EC2 VMs that are hosting the cluster's containers is running v1.17.2 of the ECS Agent, current version is 1.17.3.  Given we're almost certainly not using the current [ECS-Optimized AMI](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-update.html#checking_agent_version), we would have to have the current SSH keypair available to us to update these VMs.  Unfortunately, the private key for _hackoregon-integration-ecs_ was never transferred from last year's keymaster, so this cluster will ultimately have to be rebuilt if we're to update any of the OS-level artifacts like this.

**Comment by iant01** [comment]
This issue the item I pointed out almost at the begining of the devop team forming but was deemed by others to not be an issue. The ecs agent can be updated from the aws console and does not require bringing down the ecs cluster.

**Comment by iant01** [comment]
Handled by issue #145 
closing issue.
